// ============================================================================
// COUNTRY EDUCATION PACK: GHANA (GH)
// Ministry of Education / Ghana Education Service (GES) / NaCCA / WAEC
// ============================================================================

import { CountryEducationFramework } from '../types';

export const ghanaFrameworkPack: CountryEducationFramework = {
  countryCode: 'GH',
  countryName: 'Ghana',
  officialFlagEmoji: '🇬🇭',
  nationalEducationAuthority: 'Ministry of Education / Ghana Education Service (GES) / NaCCA / WAEC',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'twi', name: 'Twi (Asante/Akuapem)', isOfficial: false },
    { code: 'fnt', name: 'Fante', isOfficial: false },
    { code: 'gaa', name: 'Ga', isOfficial: false },
    { code: 'ewe', name: 'Ewe', isOfficial: false },
    { code: 'dag', name: 'Dagbani', isOfficial: false },
  ],
  timeZone: 'Africa/Accra',
  currency: {
    code: 'GHS',
    symbol: 'GH₵',
    name: 'Ghana Cedi',
    decimals: 2,
    formatPattern: '#,##0.00',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'SEMESTERS_2',
    termsCount: 2,
    academicYearStartMonth: 'January',
    academicYearFormat: 'SINGLE_YEAR',
    defaultHolidaysWeeks: 4,
    terms: [
      { termNumber: 1, name: 'Semester 1', defaultStartMonth: 'January', defaultEndMonth: 'June', weeksDuration: 20 },
      { termNumber: 2, name: 'Semester 2', defaultStartMonth: 'July', defaultEndMonth: 'December', weeksDuration: 20 },
    ],
  },
  educationLevels: [
    {
      id: 'gh-kg',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Kindergarten (KG 1 - KG 2)',
      typicalAgeRange: '4 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'KG1', displayName: 'Kindergarten 1', code: 'KG1', standardAge: 4 },
        { gradeKey: 'KG2', displayName: 'Kindergarten 2', code: 'KG2', standardAge: 5 },
      ],
    },
    {
      id: 'gh-primary',
      levelKey: 'PRIMARY',
      displayName: 'Primary School (Basic 1 - 6)',
      typicalAgeRange: '6 - 11 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'B1', displayName: 'Basic 1', code: 'B1', standardAge: 6 },
        { gradeKey: 'B2', displayName: 'Basic 2', code: 'B2', standardAge: 7 },
        { gradeKey: 'B3', displayName: 'Basic 3', code: 'B3', standardAge: 8 },
        { gradeKey: 'B4', displayName: 'Basic 4', code: 'B4', standardAge: 9 },
        { gradeKey: 'B5', displayName: 'Basic 5', code: 'B5', standardAge: 10 },
        { gradeKey: 'B6', displayName: 'Basic 6', code: 'B6', standardAge: 11 },
      ],
    },
    {
      id: 'gh-jhs',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Junior High School (JHS 1 - 3 BECE)',
      typicalAgeRange: '12 - 14 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'JHS1', displayName: 'JHS 1 (Basic 7)', code: 'JHS1', standardAge: 12 },
        { gradeKey: 'JHS2', displayName: 'JHS 2 (Basic 8)', code: 'JHS2', standardAge: 13 },
        { gradeKey: 'JHS3', displayName: 'JHS 3 (Basic 9 / BECE Candidate)', code: 'JHS3', standardAge: 14 },
      ],
    },
    {
      id: 'gh-shs',
      levelKey: 'SENIOR_SECONDARY',
      displayName: 'Senior High School (SHS 1 - 3 WASSCE)',
      typicalAgeRange: '15 - 17 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'SHS1', displayName: 'SHS 1 (Form 1)', code: 'SHS1', standardAge: 15 },
        { gradeKey: 'SHS2', displayName: 'SHS 2 (Form 2)', code: 'SHS2', standardAge: 16 },
        { gradeKey: 'SHS3', displayName: 'SHS 3 (Form 3 / WASSCE Candidate)', code: 'SHS3', standardAge: 17 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'gh-nacca-ccp',
      code: 'NaCCA-CCP-GH',
      name: 'NaCCA Standards-Based & Common Core Programme (CCP)',
      countryCode: 'GH',
      type: 'STANDARDS_BASED',
      authority: 'National Council for Curriculum and Assessment (NaCCA)',
      description: 'Standards-based curriculum focusing on 4Rs (Reading, wRiting, aRithmetic, and cReativity) and 21st-century core competencies.',
      isNationalStandard: true,
      version: '2023.v2',
      effectiveYear: 2020,
      applicableLevels: ['gh-primary', 'gh-jhs', 'gh-shs'],
      subjects: [
        { code: 'ENG-GH', name: 'English Language', category: 'Core', isCompulsory: true },
        { code: 'MTH-GH', name: 'Mathematics', category: 'Core', isCompulsory: true },
        { code: 'SCI-GH', name: 'Integrated Science', category: 'Core', isCompulsory: true },
        { code: 'SOC-GH', name: 'Social Studies', category: 'Core', isCompulsory: true },
        { code: 'RME-GH', name: 'Religious and Moral Education (RME)', category: 'Core', isCompulsory: true },
        { code: 'CAD-GH', name: 'Creative Arts and Design', category: 'Co-Curricular', isCompulsory: true },
        { code: 'CAT-GH', name: 'Career Technology & Computing', category: 'Vocational', isCompulsory: true },
        { code: 'GH-LANG', name: 'Ghanaian Language and Culture', category: 'Elective', isCompulsory: false },
        { code: 'FR-GH', name: 'French Language', category: 'Elective', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'gh-waec-stanine-9',
      name: 'WAEC BECE 9-Point Stanine Scale (Grade 1 - 9)',
      scaleType: 'STANINE_GRADES_9',
      description: 'Official WAEC BECE Stanine grading system for secondary school placement (CSSPS).',
      continuousAssessmentWeightPercent: 30,
      examinationWeightPercent: 70,
      supportsRubrics: false,
      scales: [
        { grade: 'Grade 1', minPercentage: 80, maxPercentage: 100, points: 1, descriptor: 'Highest / Excellent', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'Grade 2', minPercentage: 70, maxPercentage: 79, points: 2, descriptor: 'Higher / Very Good', classification: 'Distinction', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'Grade 3', minPercentage: 65, maxPercentage: 69, points: 3, descriptor: 'High / Good', classification: 'Credit', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'Grade 4', minPercentage: 60, maxPercentage: 64, points: 4, descriptor: 'High Average / Credit', classification: 'Credit', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'Grade 5', minPercentage: 55, maxPercentage: 59, points: 5, descriptor: 'Average / Credit', classification: 'Credit', colorHex: '#60A5FA', isPassingGrade: true },
        { grade: 'Grade 6', minPercentage: 50, maxPercentage: 54, points: 6, descriptor: 'Low Average / Credit', classification: 'Credit', colorHex: '#93C5FD', isPassingGrade: true },
        { grade: 'Grade 7', minPercentage: 45, maxPercentage: 49, points: 7, descriptor: 'Low / Pass', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'Grade 8', minPercentage: 40, maxPercentage: 44, points: 8, descriptor: 'Lower / Pass', classification: 'Pass', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'Grade 9', minPercentage: 0, maxPercentage: 39, points: 9, descriptor: 'Lowest / Fail', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Subject',
    subjectsLabelPlural: 'Subjects',
    gradeLabel: 'Class / Form',
    termLabel: 'Semester / Term',
    headOfSchoolLabel: 'Headmaster / Headmistress',
    deputyHeadLabel: 'Assistant Head (Academic)',
    directorOfStudiesLabel: 'Academic Head',
    reportCardLabel: 'Terminal Assessment Report',
    nationalExamLabel: 'WAEC BECE / WASSCE Examination',
    bursarLabel: 'Bursar / Accountant',
  },
  paymentGateways: [
    {
      providerId: 'mtn-momo-gh',
      displayName: 'MTN Mobile Money Ghana',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['MTN MoMo Prompt', 'Merchant PayCode'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'GHS',
    },
    {
      providerId: 'paystack-gh',
      displayName: 'Paystack Ghana (Cards & Mobile Wallets)',
      type: 'HYBRID_GATEWAY',
      isPopularInCountry: true,
      supportedMethods: ['Visa/Mastercard', 'MTN MoMo', 'Vodafone Cash', 'AirtelTigo'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'GHS',
    },
    {
      providerId: 'vodafone-cash-gh',
      displayName: 'Telecel / Vodafone Cash Ghana',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Vodafone Cash STK'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'GHS',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'gh-emis-ges',
      systemName: 'Ghana EMIS GES Portal',
      authorityName: 'Ghana Education Service Statistics Division',
      supportedFormats: ['XML', 'CSV', 'JSON', 'PDF'],
      complianceVersion: 'EMIS-GH-2025',
      samplePayloadSummary: 'Basic education school census, capitation grant registers, teacher qualifications, school feeding beneficiary counts.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Data Protection Act, 2012 (Act 843) Ghana',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 7,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.0.0',
  lastUpdated: '2026-08-18',
};
