// ============================================================================
// COUNTRY EDUCATION PACK: INTERNATIONAL / GLOBAL (INTL)
// Cambridge Assessment, International Baccalaureate (IB), American K-12
// ============================================================================

import { CountryEducationFramework } from '../types';

export const internationalFrameworkPack: CountryEducationFramework = {
  countryCode: 'INTL',
  countryName: 'International / Global Curriculum',
  officialFlagEmoji: '🌐',
  nationalEducationAuthority: 'Cambridge International / International Baccalaureate (IBO) / Cognia',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'fr', name: 'French', isOfficial: true },
    { code: 'es', name: 'Spanish', isOfficial: true },
    { code: 'zh', name: 'Mandarin Chinese', isOfficial: false },
    { code: 'ar', name: 'Arabic', isOfficial: false },
  ],
  timeZone: 'UTC',
  currency: {
    code: 'USD',
    symbol: '$',
    name: 'US Dollar',
    decimals: 2,
    formatPattern: '#,##0.00',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'TERMS_3',
    termsCount: 3,
    academicYearStartMonth: 'September',
    academicYearFormat: 'SPLIT_YEAR',
    defaultHolidaysWeeks: 4,
    terms: [
      { termNumber: 1, name: 'Autumn Term (Term 1)', defaultStartMonth: 'September', defaultEndMonth: 'December', weeksDuration: 14 },
      { termNumber: 2, name: 'Spring Term (Term 2)', defaultStartMonth: 'January', defaultEndMonth: 'March', weeksDuration: 11 },
      { termNumber: 3, name: 'Summer Term (Term 3)', defaultStartMonth: 'April', defaultEndMonth: 'June', weeksDuration: 11 },
    ],
  },
  educationLevels: [
    {
      id: 'intl-eyfs',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Early Years Foundation Stage (EYFS / Pre-K)',
      typicalAgeRange: '3 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'NURSERY', displayName: 'Nursery (FS1)', code: 'FS1', standardAge: 3 },
        { gradeKey: 'RECEPTION', displayName: 'Reception / KG (FS2)', code: 'FS2', standardAge: 4 },
      ],
    },
    {
      id: 'intl-primary',
      levelKey: 'PRIMARY',
      displayName: 'Primary / Cambridge Primary / IB PYP (Year 1 - 6)',
      typicalAgeRange: '5 - 11 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'YEAR_1', displayName: 'Year 1 / Grade 1', code: 'Y1', standardAge: 5 },
        { gradeKey: 'YEAR_2', displayName: 'Year 2 / Grade 2', code: 'Y2', standardAge: 6 },
        { gradeKey: 'YEAR_3', displayName: 'Year 3 / Grade 3', code: 'Y3', standardAge: 7 },
        { gradeKey: 'YEAR_4', displayName: 'Year 4 / Grade 4', code: 'Y4', standardAge: 8 },
        { gradeKey: 'YEAR_5', displayName: 'Year 5 / Grade 5', code: 'Y5', standardAge: 9 },
        { gradeKey: 'YEAR_6', displayName: 'Year 6 / Grade 6 (Primary Checkpoint)', code: 'Y6', standardAge: 10 },
      ],
    },
    {
      id: 'intl-lower-sec',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Lower Secondary / Cambridge Lower / IB MYP (Year 7 - 9)',
      typicalAgeRange: '11 - 14 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'YEAR_7', displayName: 'Year 7 / Grade 7', code: 'Y7', standardAge: 11 },
        { gradeKey: 'YEAR_8', displayName: 'Year 8 / Grade 8', code: 'Y8', standardAge: 12 },
        { gradeKey: 'YEAR_9', displayName: 'Year 9 / Grade 9 (Lower Secondary Checkpoint)', code: 'Y9', standardAge: 13 },
      ],
    },
    {
      id: 'intl-igcse',
      levelKey: 'UPPER_SECONDARY',
      displayName: 'Upper Secondary / Cambridge IGCSE (Year 10 - 11)',
      typicalAgeRange: '14 - 16 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'YEAR_10', displayName: 'Year 10 (IGCSE Year 1)', code: 'Y10', standardAge: 14 },
        { gradeKey: 'YEAR_11', displayName: 'Year 11 (IGCSE Final Candidate)', code: 'Y11', standardAge: 15 },
      ],
    },
    {
      id: 'intl-sixth-form',
      levelKey: 'SIXTH_FORM',
      displayName: 'Sixth Form / Cambridge International A-Levels / IB DP (Year 12 - 13)',
      typicalAgeRange: '16 - 18 Years',
      sortOrder: 5,
      grades: [
        { gradeKey: 'YEAR_12', displayName: 'Year 12 (AS-Level / IB DP 1)', code: 'Y12', standardAge: 16 },
        { gradeKey: 'YEAR_13', displayName: 'Year 13 (A2-Level / IB DP 2 Final)', code: 'Y13', standardAge: 17 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'intl-cambridge-igcse',
      code: 'CAMBRIDGE-IGCSE',
      name: 'Cambridge Assessment International Education (IGCSE & A-Level)',
      countryCode: 'INTL',
      type: 'CAMBRIDGE_INTERNATIONAL',
      authority: 'Cambridge University Press & Assessment',
      description: 'Globally recognized curriculum with international standards, rigorous subject exams, and world-renowned qualifications.',
      isNationalStandard: false,
      version: 'Cambridge.2025',
      effectiveYear: 2020,
      applicableLevels: ['intl-primary', 'intl-lower-sec', 'intl-igcse', 'intl-sixth-form'],
      subjects: [
        { code: '0500', name: 'First Language English (0500)', category: 'Core', isCompulsory: true },
        { code: '0580', name: 'Mathematics (0580)', category: 'Core', isCompulsory: true },
        { code: '0625', name: 'Physics (0625)', category: 'Core', isCompulsory: false },
        { code: '0620', name: 'Chemistry (0620)', category: 'Core', isCompulsory: false },
        { code: '0610', name: 'Biology (0610)', category: 'Core', isCompulsory: false },
        { code: '0478', name: 'Computer Science (0478)', category: 'Vocational', isCompulsory: false },
        { code: '0450', name: 'Business Studies (0450)', category: 'Elective', isCompulsory: false },
        { code: '0455', name: 'Economics (0455)', category: 'Elective', isCompulsory: false },
        { code: '0470', name: 'History (0470)', category: 'Elective', isCompulsory: false },
      ],
    },
    {
      id: 'intl-ib-diploma',
      code: 'IB-DP-WORLD',
      name: 'International Baccalaureate Diploma Programme (IB DP)',
      countryCode: 'INTL',
      type: 'INTERNATIONAL_BACCALAUREATE',
      authority: 'International Baccalaureate Organization (IBO)',
      description: 'Comprehensive academic program spanning 6 subject groups plus the DP Core (Theory of Knowledge, Extended Essay, CAS).',
      isNationalStandard: false,
      version: 'IB.DP.2024',
      effectiveYear: 2021,
      applicableLevels: ['intl-sixth-form'],
      subjects: [
        { code: 'IB-ENG', name: 'Language A: Literature (HL/SL)', category: 'Core', isCompulsory: true },
        { code: 'IB-MATH', name: 'Mathematics: Analysis and Approaches (HL/SL)', category: 'Core', isCompulsory: true },
        { code: 'IB-SCI', name: 'Experimental Sciences (Physics/Chemistry/Biology)', category: 'Core', isCompulsory: true },
        { code: 'IB-INDIV', name: 'Individuals and Societies (Economics/History/Psychology)', category: 'Elective', isCompulsory: true },
        { code: 'IB-TOK', name: 'Theory of Knowledge (TOK Core)', category: 'Core', isCompulsory: true },
        { code: 'IB-EE', name: 'Extended Essay (EE Core)', category: 'Core', isCompulsory: true },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'intl-cambridge-scale',
      name: 'Cambridge International Grading Scale (A* to G / U)',
      scaleType: 'CAMBRIDGE_IGCSE',
      description: 'Standard Cambridge IGCSE international grading benchmark with percentage uniform marks (PUM).',
      continuousAssessmentWeightPercent: 20,
      examinationWeightPercent: 80,
      supportsRubrics: true,
      scales: [
        { grade: 'A*', minPercentage: 90, maxPercentage: 100, points: 9, descriptor: 'Outstanding / Exceptional Performance', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'A', minPercentage: 80, maxPercentage: 89, points: 8, descriptor: 'Excellent Mastery of Curriculum', classification: 'Distinction', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'B', minPercentage: 70, maxPercentage: 79, points: 7, descriptor: 'Very Good Competence and Application', classification: 'Merit', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'C', minPercentage: 60, maxPercentage: 69, points: 6, descriptor: 'Good Standard Passing Level', classification: 'Credit', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'D', minPercentage: 50, maxPercentage: 59, points: 5, descriptor: 'Moderate Achievement', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'E', minPercentage: 40, maxPercentage: 49, points: 4, descriptor: 'Minimum Acceptable Standard', classification: 'Pass', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'F', minPercentage: 30, maxPercentage: 39, points: 3, descriptor: 'Weak Performance', classification: 'Marginal', colorHex: '#D97706', isPassingGrade: true },
        { grade: 'G', minPercentage: 20, maxPercentage: 29, points: 2, descriptor: 'Low Achievement', classification: 'Marginal', colorHex: '#B45309', isPassingGrade: true },
        { grade: 'U', minPercentage: 0, maxPercentage: 19, points: 0, descriptor: 'Ungraded / Fail', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
    {
      id: 'intl-ib-7point',
      name: 'International Baccalaureate 7-Point Scale (7 to 1)',
      scaleType: 'IB_POINTS_7',
      description: 'Official IB DP subject score scale from 1 (lowest) to 7 (highest), yielding a maximum total of 45 diploma points.',
      continuousAssessmentWeightPercent: 20,
      examinationWeightPercent: 80,
      supportsRubrics: true,
      scales: [
        { grade: '7 (Excellent)', minPercentage: 85, maxPercentage: 100, points: 7, descriptor: 'Excellent Achievement in all Assessment Objectives', classification: 'Excellent', colorHex: '#059669', isPassingGrade: true },
        { grade: '6 (Very Good)', minPercentage: 75, maxPercentage: 84, points: 6, descriptor: 'Very Good Achievement', classification: 'Very Good', colorHex: '#10B981', isPassingGrade: true },
        { grade: '5 (Good)', minPercentage: 65, maxPercentage: 74, points: 5, descriptor: 'Good Achievement', classification: 'Good', colorHex: '#2563EB', isPassingGrade: true },
        { grade: '4 (Satisfactory)', minPercentage: 50, maxPercentage: 64, points: 4, descriptor: 'Satisfactory (Passing standard for Diploma)', classification: 'Satisfactory', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: '3 (Mediocre)', minPercentage: 40, maxPercentage: 49, points: 3, descriptor: 'Mediocre Achievement', classification: 'Mediocre', colorHex: '#F59E0B', isPassingGrade: false },
        { grade: '2 (Poor)', minPercentage: 25, maxPercentage: 39, points: 2, descriptor: 'Poor Achievement', classification: 'Poor', colorHex: '#FBBF24', isPassingGrade: false },
        { grade: '1 (Very Poor)', minPercentage: 0, maxPercentage: 24, points: 1, descriptor: 'Very Poor Performance', classification: 'Very Poor', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Course / Subject',
    subjectsLabelPlural: 'Courses / Subjects',
    gradeLabel: 'Year Group / Grade',
    termLabel: 'Term',
    headOfSchoolLabel: 'Principal / Head of School',
    deputyHeadLabel: 'Vice Principal / Deputy Head',
    directorOfStudiesLabel: 'Academic Director / IB Coordinator',
    reportCardLabel: 'Semester Academic Progress Dossier',
    nationalExamLabel: 'Cambridge / IB World Examination',
    bursarLabel: 'Director of Finance & Operations',
  },
  paymentGateways: [
    {
      providerId: 'stripe-global',
      displayName: 'Stripe International (Visa, Mastercard, Amex, Apple Pay)',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Credit/Debit Cards', 'Apple Pay', 'Google Pay', 'SEPA Direct Debit', 'ACH'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'USD',
    },
    {
      providerId: 'flywire-intl',
      displayName: 'Flywire International Student Tuition Portal',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Cross-Border Bank Wire', 'Multi-Currency Settlement'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'USD',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'intl-cie-direct-export',
      systemName: 'Cambridge CIE Direct & IBIS Candidate Data Exchange',
      authorityName: 'International Examination Boards',
      supportedFormats: ['CSV', 'JSON', 'XML', 'PDF'],
      complianceVersion: 'CIE-DIRECT-2025',
      samplePayloadSummary: 'International candidate entry codes, Predicted grades, Coursework marks, Internal Assessment sample moderation sheets.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'General Data Protection Regulation (GDPR) / International Best Practice',
    dataResidencyDefaultRegion: 'europe-west1',
    parentalConsentAgeThreshold: 16,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.5.0',
  lastUpdated: '2026-08-18',
};
