// ============================================================================
// COUNTRY EDUCATION PACK: KENYA (KE)
// Ministry of Education / KNEC / KICD (CBC 2-6-3-3-3 & 8-4-4)
// ============================================================================

import { CountryEducationFramework } from '../types';

export const kenyaFrameworkPack: CountryEducationFramework = {
  countryCode: 'KE',
  countryName: 'Kenya',
  officialFlagEmoji: '🇰🇪',
  nationalEducationAuthority: 'Ministry of Education (MoE) / KNEC / KICD',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'sw', name: 'Kiswahili', isOfficial: true },
    { code: 'ki', name: 'Gikuyu', isOfficial: false },
    { code: 'luo', name: 'Dholuo', isOfficial: false },
    { code: 'luy', name: 'Luhya', isOfficial: false },
  ],
  timeZone: 'Africa/Nairobi',
  currency: {
    code: 'KES',
    symbol: 'KSh',
    name: 'Kenyan Shilling',
    decimals: 2,
    formatPattern: '#,##0.00',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'TERMS_3',
    termsCount: 3,
    academicYearStartMonth: 'January',
    academicYearFormat: 'SINGLE_YEAR',
    defaultHolidaysWeeks: 3,
    terms: [
      { termNumber: 1, name: 'Term 1', defaultStartMonth: 'January', defaultEndMonth: 'April', weeksDuration: 13 },
      { termNumber: 2, name: 'Term 2', defaultStartMonth: 'May', defaultEndMonth: 'August', weeksDuration: 14 },
      { termNumber: 3, name: 'Term 3', defaultStartMonth: 'September', defaultEndMonth: 'November', weeksDuration: 9 },
    ],
  },
  educationLevels: [
    {
      id: 'ke-pp',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Pre-Primary Education (CBC)',
      typicalAgeRange: '4 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'PP1', displayName: 'Pre-Primary 1', code: 'PP1', standardAge: 4 },
        { gradeKey: 'PP2', displayName: 'Pre-Primary 2', code: 'PP2', standardAge: 5 },
      ],
    },
    {
      id: 'ke-primary',
      levelKey: 'PRIMARY',
      displayName: 'Primary Education (Grade 1 - 6)',
      typicalAgeRange: '6 - 11 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'G1', displayName: 'Grade 1', code: 'G1', standardAge: 6 },
        { gradeKey: 'G2', displayName: 'Grade 2', code: 'G2', standardAge: 7 },
        { gradeKey: 'G3', displayName: 'Grade 3', code: 'G3', standardAge: 8 },
        { gradeKey: 'G4', displayName: 'Grade 4', code: 'G4', standardAge: 9 },
        { gradeKey: 'G5', displayName: 'Grade 5', code: 'G5', standardAge: 10 },
        { gradeKey: 'G6', displayName: 'Grade 6 (KPSEA Assessment)', code: 'G6', standardAge: 11 },
      ],
    },
    {
      id: 'ke-jss',
      levelKey: 'JUNIOR_SECONDARY',
      displayName: 'Junior School (JSS Grade 7 - 9)',
      typicalAgeRange: '12 - 14 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'G7', displayName: 'Grade 7 (Junior School)', code: 'G7', standardAge: 12 },
        { gradeKey: 'G8', displayName: 'Grade 8 (Junior School)', code: 'G8', standardAge: 13 },
        { gradeKey: 'G9', displayName: 'Grade 9 (KJSEA Candidate)', code: 'G9', standardAge: 14 },
      ],
    },
    {
      id: 'ke-sss',
      levelKey: 'SENIOR_SECONDARY',
      displayName: 'Senior School / Pathways (Grade 10 - 12)',
      typicalAgeRange: '15 - 17 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'G10', displayName: 'Grade 10 (Senior School)', code: 'G10', standardAge: 15 },
        { gradeKey: 'G11', displayName: 'Grade 11 (Senior School)', code: 'G11', standardAge: 16 },
        { gradeKey: 'G12', displayName: 'Grade 12 (National Assessment)', code: 'G12', standardAge: 17 },
      ],
    },
    {
      id: 'ke-tvet',
      levelKey: 'TECHNICAL_VOCATIONAL',
      displayName: 'TVET / Vocational College',
      typicalAgeRange: '18+ Years',
      sortOrder: 5,
      grades: [
        { gradeKey: 'TVET_1', displayName: 'Artisan / Craft Certificate', code: 'TC1', standardAge: 18 },
        { gradeKey: 'TVET_2', displayName: 'National Diploma', code: 'TD2', standardAge: 19 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'ke-kicd-cbc',
      code: 'KICD-CBC-2024',
      name: 'Kenya Competency-Based Curriculum (CBC 2-6-3-3)',
      countryCode: 'KE',
      type: 'COMPETENCY_BASED',
      authority: 'Kenya Institute of Curriculum Development (KICD)',
      description: 'Learner-centred curriculum developing 7 core competencies (Communication, Critical Thinking, Creativity, Citizenship, Digital Literacy, Learning to Learn, Self-efficacy).',
      isNationalStandard: true,
      version: '2024.v3',
      effectiveYear: 2019,
      applicableLevels: ['ke-primary', 'ke-jss', 'ke-sss'],
      subjects: [
        { code: 'ENG-LA', name: 'English Language', category: 'Core', isCompulsory: true, strandsOrTopics: ['Listening & Speaking', 'Reading Comprehension', 'Language Structures', 'Writing'] },
        { code: 'KISW-LA', name: 'Kiswahili / KSL', category: 'Core', isCompulsory: true, strandsOrTopics: ['Kusikiliza na Kuzungumza', 'Kusoma', 'Sarufi', 'Kuandika'] },
        { code: 'MATH-LA', name: 'Mathematics', category: 'Core', isCompulsory: true, strandsOrTopics: ['Numbers', 'Algebra', 'Measurements', 'Geometry', 'Data Handling'] },
        { code: 'IS-LA', name: 'Integrated Science', category: 'Core', isCompulsory: true, strandsOrTopics: ['Living Things', 'Matter & Energy', 'Earth & Space', 'Science Investigations'] },
        { code: 'SST-LA', name: 'Social Studies & Life Skills', category: 'Core', isCompulsory: true, strandsOrTopics: ['Governance', 'Environment', 'Human Rights', 'Global Citizenship'] },
        { code: 'CRE-LA', name: 'Christian Religious Education', category: 'Elective', isCompulsory: false },
        { code: 'IRE-LA', name: 'Islamic Religious Education', category: 'Elective', isCompulsory: false },
        { code: 'AGR-LA', name: 'Agriculture & Nutrition', category: 'Vocational', isCompulsory: true, strandsOrTopics: ['Crop Production', 'Animal Husbandry', 'Food Processing'] },
        { code: 'CA-LA', name: 'Creative Arts & Sports', category: 'Co-Curricular', isCompulsory: true, strandsOrTopics: ['Music', 'Visual Arts', 'Physical Education'] },
        { code: 'PA-LA', name: 'Pre-Technical Studies & Computer Science', category: 'Vocational', isCompulsory: true, strandsOrTopics: ['Materials & Tools', 'Digital Skills', 'Coding & Electronics'] },
      ],
    },
    {
      id: 'ke-knec-kcse-844',
      code: 'KNEC-KCSE-844',
      name: 'Kenya Certificate of Secondary Education (KCSE 8-4-4)',
      countryCode: 'KE',
      type: 'TRADITIONAL_SUBJECT_BASED',
      authority: 'Kenya National Examinations Council (KNEC)',
      description: 'Secondary school curriculum with national examinations and 12-point grading scale.',
      isNationalStandard: true,
      version: '8-4-4.v2',
      effectiveYear: 1985,
      applicableLevels: ['ke-sss'],
      subjects: [
        { code: '101', name: 'English', category: 'Core', isCompulsory: true },
        { code: '102', name: 'Kiswahili', category: 'Core', isCompulsory: true },
        { code: '121', name: 'Mathematics Alt A', category: 'Core', isCompulsory: true },
        { code: '231', name: 'Biology', category: 'Core', isCompulsory: false },
        { code: '232', name: 'Physics', category: 'Core', isCompulsory: false },
        { code: '233', name: 'Chemistry', category: 'Core', isCompulsory: false },
        { code: '311', name: 'History and Government', category: 'Elective', isCompulsory: false },
        { code: '312', name: 'Geography', category: 'Elective', isCompulsory: false },
        { code: '565', name: 'Business Studies', category: 'Vocational', isCompulsory: false },
        { code: '451', name: 'Computer Studies', category: 'Vocational', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'ke-cbc-4levels',
      name: 'Kenya CBC 4-Level Competency Rubric (EE, ME, AE, BE)',
      scaleType: 'COMPETENCY_LEVELS_4',
      description: 'Official KICD/KNEC Competency-Based Assessment rating criteria measuring learners against explicit performance benchmarks.',
      continuousAssessmentWeightPercent: 60,
      examinationWeightPercent: 40,
      supportsRubrics: true,
      scales: [
        { grade: 'EE (Level 4)', minPercentage: 80, maxPercentage: 100, points: 4, descriptor: 'Exceeding Expectations (Demonstrates mastery beyond standard requirements and guides peers)', classification: 'Exceeding Expectations', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'ME (Level 3)', minPercentage: 60, maxPercentage: 79, points: 3, descriptor: 'Meeting Expectations (Independently completes all tasks and applies competencies correctly)', classification: 'Meeting Expectations', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'AE (Level 2)', minPercentage: 40, maxPercentage: 59, points: 2, descriptor: 'Approaching Expectations (Performs task with minor assistance; partial understanding)', classification: 'Approaching Expectations', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'BE (Level 1)', minPercentage: 0, maxPercentage: 39, points: 1, descriptor: 'Below Expectations (Requires continuous teacher support and guided remediation)', classification: 'Below Expectations', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
    {
      id: 'ke-knec-kcse-12point',
      name: 'KNEC KCSE 12-Point Grade Scale (A through E)',
      scaleType: 'LETTER_GRADES_12',
      description: 'Standard 12-point secondary examination grading system used by KNEC for KCSE Mean Grade and university placement (KUCCPS).',
      continuousAssessmentWeightPercent: 30,
      examinationWeightPercent: 70,
      supportsRubrics: false,
      scales: [
        { grade: 'A', minPercentage: 80, maxPercentage: 100, points: 12, descriptor: 'Excellent (Plain A)', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'A-', minPercentage: 75, maxPercentage: 79, points: 11, descriptor: 'A Minus', classification: 'Distinction', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'B+', minPercentage: 70, maxPercentage: 74, points: 10, descriptor: 'B Plus', classification: 'Credit', colorHex: '#1D4ED8', isPassingGrade: true },
        { grade: 'B', minPercentage: 65, maxPercentage: 69, points: 9, descriptor: 'B Plain', classification: 'Credit', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'B-', minPercentage: 60, maxPercentage: 64, points: 8, descriptor: 'B Minus', classification: 'Credit', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'C+', minPercentage: 55, maxPercentage: 59, points: 7, descriptor: 'C Plus (University Cut-off Entry)', classification: 'Credit', colorHex: '#60A5FA', isPassingGrade: true },
        { grade: 'C', minPercentage: 50, maxPercentage: 54, points: 6, descriptor: 'C Plain', classification: 'Pass', colorHex: '#93C5FD', isPassingGrade: true },
        { grade: 'C-', minPercentage: 45, maxPercentage: 49, points: 5, descriptor: 'C Minus', classification: 'Pass', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'D+', minPercentage: 40, maxPercentage: 44, points: 4, descriptor: 'D Plus', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'D', minPercentage: 35, maxPercentage: 39, points: 3, descriptor: 'D Plain', classification: 'Pass', colorHex: '#D97706', isPassingGrade: true },
        { grade: 'D-', minPercentage: 30, maxPercentage: 34, points: 2, descriptor: 'D Minus', classification: 'Marginal Pass', colorHex: '#B45309', isPassingGrade: true },
        { grade: 'E', minPercentage: 0, maxPercentage: 29, points: 1, descriptor: 'Fail (E)', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Learning Area',
    subjectsLabelPlural: 'Learning Areas',
    gradeLabel: 'Grade',
    termLabel: 'Term',
    headOfSchoolLabel: 'Principal',
    deputyHeadLabel: 'Deputy Principal',
    directorOfStudiesLabel: 'Dean of Studies',
    reportCardLabel: 'Summative & Formative Progress Report',
    nationalExamLabel: 'KNEC Assessment (KPSEA/KJSEA/KCSE)',
    bursarLabel: 'Finance Officer',
  },
  paymentGateways: [
    {
      providerId: 'safaricom-mpesa-ke',
      displayName: 'Safaricom M-Pesa (Till / Paybill STK Push)',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['M-Pesa STK Push Express', 'Paybill Number', 'Buy Goods Till'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'KES',
    },
    {
      providerId: 'pesapal-ke',
      displayName: 'Pesapal Kenya (Visa, Mastercard, M-Pesa, Airtel)',
      type: 'PESAPAL',
      isPopularInCountry: true,
      supportedMethods: ['M-Pesa', 'Airtel Money', 'Visa/Mastercard', 'KCB App', 'Equity EazzyPay'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'KES',
    },
    {
      providerId: 'airtel-money-ke',
      displayName: 'Airtel Money Kenya STK',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Airtel Money STK Push'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'KES',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'ke-nemis-sync',
      systemName: 'National Education Management Information System (NEMIS)',
      authorityName: 'Kenya Ministry of Education ICT Directorate',
      supportedFormats: ['JSON', 'CSV', 'XML'],
      complianceVersion: 'NEMIS-v3.1-CBC',
      samplePayloadSummary: 'Learner Unique Personal Identifier (UPI), Parent ID details, Capitation Free Day Secondary allocation registers, CBC tracking data.',
    },
    {
      adapterId: 'ke-knec-cba-portal',
      systemName: 'KNEC Competency-Based Assessment (CBA) Portal Export',
      authorityName: 'Kenya National Examinations Council',
      supportedFormats: ['CSV', 'XML', 'PDF'],
      complianceVersion: 'KNEC-CBA-2025',
      samplePayloadSummary: 'Scores for Project-based assessments, Learner Portfolios, Grade 6 KPSEA / Grade 9 KJSEA candidate register.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Kenya Data Protection Act, 2019 (ODPC Kenya)',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.5.0',
  lastUpdated: '2026-08-18',
};
