// ============================================================================
// COUNTRY EDUCATION PACK: NIGERIA (NG)
// Federal Ministry of Education / NERDC / WAEC / NECO / UBEC
// ============================================================================

import { CountryEducationFramework } from '../types';

export const nigeriaFrameworkPack: CountryEducationFramework = {
  countryCode: 'NG',
  countryName: 'Nigeria',
  officialFlagEmoji: '🇳🇬',
  nationalEducationAuthority: 'Federal Ministry of Education (FME) / NERDC / WAEC / NECO / UBEC',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'yo', name: 'Yoruba', isOfficial: false },
    { code: 'ha', name: 'Hausa', isOfficial: false },
    { code: 'ig', name: 'Igbo', isOfficial: false },
    { code: 'pcm', name: 'Nigerian Pidgin', isOfficial: false },
  ],
  timeZone: 'Africa/Lagos',
  currency: {
    code: 'NGN',
    symbol: '₦',
    name: 'Nigerian Naira',
    decimals: 2,
    formatPattern: '#,##0.00',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'TERMS_3',
    termsCount: 3,
    academicYearStartMonth: 'September',
    academicYearFormat: 'SPLIT_YEAR',
    defaultHolidaysWeeks: 3,
    terms: [
      { termNumber: 1, name: '1st Term', defaultStartMonth: 'September', defaultEndMonth: 'December', weeksDuration: 13 },
      { termNumber: 2, name: '2nd Term', defaultStartMonth: 'January', defaultEndMonth: 'April', weeksDuration: 13 },
      { termNumber: 3, name: '3rd Term', defaultStartMonth: 'May', defaultEndMonth: 'July', weeksDuration: 12 },
    ],
  },
  educationLevels: [
    {
      id: 'ng-eyfs',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Early Childhood Care & Development (ECCD)',
      typicalAgeRange: '3 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'NURSERY_1', displayName: 'Nursery 1', code: 'N1', standardAge: 3 },
        { gradeKey: 'NURSERY_2', displayName: 'Nursery 2 (KG)', code: 'N2', standardAge: 4 },
      ],
    },
    {
      id: 'ng-basic-primary',
      levelKey: 'PRIMARY',
      displayName: 'Universal Basic Education: Primary (Basic 1 - 6)',
      typicalAgeRange: '6 - 11 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'BASIC_1', displayName: 'Basic 1 (Primary 1)', code: 'B1', standardAge: 6 },
        { gradeKey: 'BASIC_2', displayName: 'Basic 2 (Primary 2)', code: 'B2', standardAge: 7 },
        { gradeKey: 'BASIC_3', displayName: 'Basic 3 (Primary 3)', code: 'B3', standardAge: 8 },
        { gradeKey: 'BASIC_4', displayName: 'Basic 4 (Primary 4)', code: 'B4', standardAge: 9 },
        { gradeKey: 'BASIC_5', displayName: 'Basic 5 (Primary 5)', code: 'B5', standardAge: 10 },
        { gradeKey: 'BASIC_6', displayName: 'Basic 6 (Primary 6 / NCEE)', code: 'B6', standardAge: 11 },
      ],
    },
    {
      id: 'ng-jss',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Junior Secondary School (JSS 1 - 3 / BECE)',
      typicalAgeRange: '12 - 14 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'JSS_1', displayName: 'JSS 1 (Basic 7)', code: 'JSS1', standardAge: 12 },
        { gradeKey: 'JSS_2', displayName: 'JSS 2 (Basic 8)', code: 'JSS2', standardAge: 13 },
        { gradeKey: 'JSS_3', displayName: 'JSS 3 (Basic 9 / BECE Candidate)', code: 'JSS3', standardAge: 14 },
      ],
    },
    {
      id: 'ng-sss',
      levelKey: 'SENIOR_SECONDARY',
      displayName: 'Senior Secondary School (SSS 1 - 3 / WAEC & NECO)',
      typicalAgeRange: '15 - 17 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'SSS_1', displayName: 'SSS 1 (Year 10)', code: 'SSS1', standardAge: 15 },
        { gradeKey: 'SSS_2', displayName: 'SSS 2 (Year 11)', code: 'SSS2', standardAge: 16 },
        { gradeKey: 'SSS_3', displayName: 'SSS 3 (Year 12 / WASSCE & SSCE Candidate)', code: 'SSS3', standardAge: 17 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'ng-nerdc-national',
      code: 'NERDC-NAT-NG',
      name: 'NERDC National Basic & Senior Secondary Curriculum',
      countryCode: 'NG',
      type: 'STANDARDS_BASED',
      authority: 'Nigerian Educational Research and Development Council (NERDC)',
      description: 'National 9-3-4 curriculum structure preparing students for BECE, WASSCE, and NECO SSCE.',
      isNationalStandard: true,
      version: '2023.v1',
      effectiveYear: 2014,
      applicableLevels: ['ng-basic-primary', 'ng-jss', 'ng-sss'],
      subjects: [
        { code: 'ENG-NG', name: 'English Language', category: 'Core', isCompulsory: true },
        { code: 'MTH-NG', name: 'General Mathematics', category: 'Core', isCompulsory: true },
        { code: 'CIVIC-NG', name: 'Civic Education', category: 'Core', isCompulsory: true },
        { code: 'BIO-NG', name: 'Biology', category: 'Core', isCompulsory: false },
        { code: 'CHE-NG', name: 'Chemistry', category: 'Core', isCompulsory: false },
        { code: 'PHY-NG', name: 'Physics', category: 'Core', isCompulsory: false },
        { code: 'ECO-NG', name: 'Economics', category: 'Core', isCompulsory: false },
        { code: 'GOV-NG', name: 'Government', category: 'Elective', isCompulsory: false },
        { code: 'LIT-NG', name: 'Literature-in-English', category: 'Elective', isCompulsory: false },
        { code: 'DAT-NG', name: 'Data Processing & Computer Studies', category: 'Vocational', isCompulsory: true },
        { code: 'TRADE-NG', name: 'Trade & Entrepreneurship Subject', category: 'Vocational', isCompulsory: true },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'ng-waec-neco-9scale',
      name: 'WAEC / NECO Senior Secondary 9-Point Scale (A1 - F9)',
      scaleType: 'PERCENTAGE_LETTER_9',
      description: 'Standard 9-point percentage grading system used across West African Senior School Certificate Examination (WASSCE) and NECO.',
      continuousAssessmentWeightPercent: 40,
      examinationWeightPercent: 60,
      supportsRubrics: false,
      scales: [
        { grade: 'A1', minPercentage: 75, maxPercentage: 100, points: 1, descriptor: 'Excellent (A1)', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'B2', minPercentage: 70, maxPercentage: 74, points: 2, descriptor: 'Very Good (B2)', classification: 'Very Good', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'B3', minPercentage: 65, maxPercentage: 69, points: 3, descriptor: 'Good (B3)', classification: 'Good', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'C4', minPercentage: 60, maxPercentage: 64, points: 4, descriptor: 'Credit (C4)', classification: 'Credit', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'C5', minPercentage: 55, maxPercentage: 59, points: 5, descriptor: 'Credit (C5)', classification: 'Credit', colorHex: '#60A5FA', isPassingGrade: true },
        { grade: 'C6', minPercentage: 50, maxPercentage: 54, points: 6, descriptor: 'Credit (C6)', classification: 'Credit', colorHex: '#93C5FD', isPassingGrade: true },
        { grade: 'D7', minPercentage: 45, maxPercentage: 49, points: 7, descriptor: 'Pass (D7)', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'E8', minPercentage: 40, maxPercentage: 44, points: 8, descriptor: 'Pass (E8)', classification: 'Pass', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'F9', minPercentage: 0, maxPercentage: 39, points: 9, descriptor: 'Fail (F9)', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Subject',
    subjectsLabelPlural: 'Subjects',
    gradeLabel: 'Class',
    termLabel: 'Term',
    headOfSchoolLabel: 'Principal',
    deputyHeadLabel: 'Vice Principal (Academics)',
    directorOfStudiesLabel: 'Academic Coordinator',
    reportCardLabel: 'Continuous Assessment & Termly Dossier',
    nationalExamLabel: 'WAEC WASSCE / NECO Examination',
    bursarLabel: 'Bursar',
  },
  paymentGateways: [
    {
      providerId: 'paystack-ng',
      displayName: 'Paystack Nigeria (Cards, Bank Transfer, USSD)',
      type: 'HYBRID_GATEWAY',
      isPopularInCountry: true,
      supportedMethods: ['Visa/Mastercard/Verve', 'NIP Direct Bank Transfer', 'USSD Codes'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'NGN',
    },
    {
      providerId: 'flutterwave-ng',
      displayName: 'Flutterwave Nigeria (Cards, Barter, USSD)',
      type: 'HYBRID_GATEWAY',
      isPopularInCountry: true,
      supportedMethods: ['Cards', 'Direct Debit', 'USSD', 'Pay with Bank Transfer'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'NGN',
    },
    {
      providerId: 'monnify-ng',
      displayName: 'Monnify TeamApt Virtual Accounts',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Dedicated Student Virtual Account Number', 'Instant Transfer'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'NGN',
    },
    {
      providerId: 'remita-ng',
      displayName: 'Remita e-Payment (RRR Code)',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Remita Retrieval Reference (RRR)', 'Internet Banking'],
      integrationStatus: 'AVAILABLE',
      currencyCode: 'NGN',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'ng-nemiss-fme',
      systemName: 'Nigeria Education Management Information System (NEMIS FME)',
      authorityName: 'Federal Ministry of Education Department of Planning and Statistics',
      supportedFormats: ['JSON', 'CSV', 'XML', 'PDF'],
      complianceVersion: 'NEMIS-NG-v2.8',
      samplePayloadSummary: 'UBEC enrollment census, National Common Entrance Exam registrations, WAEC school center validation data.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Nigeria Data Protection Act, 2023 (NDPC)',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.2.0',
  lastUpdated: '2026-08-18',
};
