// ============================================================================
// COUNTRY EDUCATION PACK: RWANDA (RW)
// Ministry of Education (MINEDUC) / NESA / REB
// ============================================================================

import { CountryEducationFramework } from '../types';

export const rwandaFrameworkPack: CountryEducationFramework = {
  countryCode: 'RW',
  countryName: 'Rwanda',
  officialFlagEmoji: '🇷🇼',
  nationalEducationAuthority: 'Ministry of Education (MINEDUC) / NESA / REB',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'kin', name: 'Kinyarwanda', isOfficial: true },
    { code: 'fr', name: 'French', isOfficial: true },
    { code: 'sw', name: 'Kiswahili', isOfficial: true },
  ],
  timeZone: 'Africa/Kigali',
  currency: {
    code: 'RWF',
    symbol: 'FRw',
    name: 'Rwandan Franc',
    decimals: 0,
    formatPattern: '#,##0',
    symbolPosition: 'SUFFIX',
  },
  calendar: {
    periodType: 'TERMS_3',
    termsCount: 3,
    academicYearStartMonth: 'September',
    academicYearFormat: 'SPLIT_YEAR',
    defaultHolidaysWeeks: 3,
    terms: [
      { termNumber: 1, name: 'Term 1 (Igihembwe cya 1)', defaultStartMonth: 'September', defaultEndMonth: 'December', weeksDuration: 13 },
      { termNumber: 2, name: 'Term 2 (Igihembwe cya 2)', defaultStartMonth: 'January', defaultEndMonth: 'April', weeksDuration: 13 },
      { termNumber: 3, name: 'Term 3 (Igihembwe cya 3)', defaultStartMonth: 'April', defaultEndMonth: 'July', weeksDuration: 13 },
    ],
  },
  educationLevels: [
    {
      id: 'rw-nursery',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Inshuke / Maternelle (Nursery N1 - N3)',
      typicalAgeRange: '3 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'N1', displayName: 'Nursery 1', code: 'N1', standardAge: 3 },
        { gradeKey: 'N2', displayName: 'Nursery 2', code: 'N2', standardAge: 4 },
        { gradeKey: 'N3', displayName: 'Nursery 3', code: 'N3', standardAge: 5 },
      ],
    },
    {
      id: 'rw-primary',
      levelKey: 'PRIMARY',
      displayName: 'Amashuri Abanza / Primary (P1 - P6)',
      typicalAgeRange: '6 - 11 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'P1', displayName: 'Primary 1 (P1)', code: 'P1', standardAge: 6 },
        { gradeKey: 'P2', displayName: 'Primary 2 (P2)', code: 'P2', standardAge: 7 },
        { gradeKey: 'P3', displayName: 'Primary 3 (P3)', code: 'P3', standardAge: 8 },
        { gradeKey: 'P4', displayName: 'Primary 4 (P4)', code: 'P4', standardAge: 9 },
        { gradeKey: 'P5', displayName: 'Primary 5 (P5)', code: 'P5', standardAge: 10 },
        { gradeKey: 'P6', displayName: 'Primary 6 (P6 National Candidate)', code: 'P6', standardAge: 11 },
      ],
    },
    {
      id: 'rw-o-level',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Icyiciro Rusange / Ordinary Level (S1 - S3)',
      typicalAgeRange: '12 - 14 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'S1', displayName: 'Senior 1 (S1)', code: 'S1', standardAge: 12 },
        { gradeKey: 'S2', displayName: 'Senior 2 (S2)', code: 'S2', standardAge: 13 },
        { gradeKey: 'S3', displayName: 'Senior 3 (S3 National Candidate)', code: 'S3', standardAge: 14 },
      ],
    },
    {
      id: 'rw-a-level',
      levelKey: 'UPPER_SECONDARY',
      displayName: 'Icyiciro Cyisumbuye / Advanced Level (S4 - S6)',
      typicalAgeRange: '15 - 17 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'S4', displayName: 'Senior 4 (S4)', code: 'S4', standardAge: 15 },
        { gradeKey: 'S5', displayName: 'Senior 5 (S5)', code: 'S5', standardAge: 16 },
        { gradeKey: 'S6', displayName: 'Senior 6 (S6 Candidate)', code: 'S6', standardAge: 17 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'rw-reb-cbc',
      code: 'REB-CBC-RW',
      name: 'Rwanda Competency-Based Curriculum (REB / NESA)',
      countryCode: 'RW',
      type: 'COMPETENCY_BASED',
      authority: 'Rwanda Basic Education Board (REB) & NESA',
      description: 'National curriculum built around generic competencies (Critical Thinking, Research, Creativity, Communication, Cooperation, Lifelong Learning).',
      isNationalStandard: true,
      version: '2022.v2',
      effectiveYear: 2016,
      applicableLevels: ['rw-primary', 'rw-o-level', 'rw-a-level'],
      subjects: [
        { code: 'ENG', name: 'English', category: 'Core', isCompulsory: true },
        { code: 'KIN', name: 'Kinyarwanda', category: 'Core', isCompulsory: true },
        { code: 'MTH', name: 'Mathematics', category: 'Core', isCompulsory: true },
        { code: 'PHY', name: 'Physics', category: 'Core', isCompulsory: true },
        { code: 'CHE', name: 'Chemistry', category: 'Core', isCompulsory: true },
        { code: 'BIO', name: 'Biology & Health Sciences', category: 'Core', isCompulsory: true },
        { code: 'ICT', name: 'Information Communication Technology (ICT)', category: 'Core', isCompulsory: true },
        { code: 'GEO', name: 'Geography & Environment', category: 'Core', isCompulsory: true },
        { code: 'HIS', name: 'History & Citizenship', category: 'Core', isCompulsory: true },
        { code: 'ENT', name: 'Entrepreneurship', category: 'Vocational', isCompulsory: true },
        { code: 'FR', name: 'French', category: 'Elective', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'rw-nesa-percentage-scale',
      name: 'Rwanda NESA Standard Grading Scale (Distinction / Satisfactory / Pass)',
      scaleType: 'CUSTOM_PERCENTAGE',
      description: 'National examination scale utilized by National Examination and School Inspection Authority (NESA).',
      continuousAssessmentWeightPercent: 30,
      examinationWeightPercent: 70,
      supportsRubrics: true,
      scales: [
        { grade: 'Distinction (80-100%)', minPercentage: 80, maxPercentage: 100, points: 1, descriptor: 'Outstanding Competence (Indashyikirwa)', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'Very Good (70-79%)', minPercentage: 70, maxPercentage: 79, points: 2, descriptor: 'Very Good Achievement', classification: 'Very Good', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'Good (60-69%)', minPercentage: 60, maxPercentage: 69, points: 3, descriptor: 'Good Competency Level', classification: 'Good', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'Satisfactory (50-59%)', minPercentage: 50, maxPercentage: 59, points: 4, descriptor: 'Satisfactory Pass (Gitsinze)', classification: 'Satisfactory', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'Unclassified (<50%)', minPercentage: 0, maxPercentage: 49, points: 5, descriptor: 'Below Minimum Standard (Ntibyatsinze)', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Subject / Isomo',
    subjectsLabelPlural: 'Subjects / Amasomo',
    gradeLabel: 'Class / Umwaka',
    termLabel: 'Term / Igihembwe',
    headOfSchoolLabel: 'Head Teacher / Directeur',
    deputyHeadLabel: 'Deputy Head Teacher',
    directorOfStudiesLabel: 'Dean of Studies (DOS)',
    reportCardLabel: 'Bulletin / Raporo y\'Amanota',
    nationalExamLabel: 'Ibizamini bya Leta (NESA National Exams)',
    bursarLabel: 'Bursar / Ushinzwe Umutungo',
  },
  paymentGateways: [
    {
      providerId: 'mtn-momo-rw',
      displayName: 'MTN Mobile Money Rwanda (MoMo Pay)',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['MTN MoMo Push', 'MoMo Pay Merchant Code'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'RWF',
    },
    {
      providerId: 'airtel-money-rw',
      displayName: 'Airtel Money Rwanda',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Airtel Money STK'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'RWF',
    },
    {
      providerId: 'bk-pay-rw',
      displayName: 'Bank of Kigali (BK Urubuto Pay)',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Urubuto Pay Code', 'BK Card / App'],
      integrationStatus: 'AVAILABLE',
      currencyCode: 'RWF',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'rw-sdms-mineduc',
      systemName: 'School Data Management System (SDMS Rwanda)',
      authorityName: 'Ministry of Education (MINEDUC ICT Directorate)',
      supportedFormats: ['JSON', 'CSV', 'XML'],
      complianceVersion: 'SDMS-v3.2',
      samplePayloadSummary: 'Learner national ID numbers, Teacher licensing data, Capitation grants verification records.',
    },
    {
      adapterId: 'rw-nesa-camis',
      systemName: 'NESA Comprehensive Assessment MIS (CA-MIS)',
      authorityName: 'National Examination and School Inspection Authority',
      supportedFormats: ['CSV', 'JSON', 'PDF'],
      complianceVersion: 'NESA-CAMIS-2025',
      samplePayloadSummary: 'Continuous assessment term marks, national exam registrations, practical lab assessment logs.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Law No 058/2021 relating to the protection of personal data and privacy (Rwanda NCSA)',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.1.0',
  lastUpdated: '2026-08-18',
};
