// ============================================================================
// COUNTRY EDUCATION PACK: SOUTH AFRICA (ZA)
// Department of Basic Education (DBE) / CAPS / Umalusi
// ============================================================================

import { CountryEducationFramework } from '../types';

export const southAfricaFrameworkPack: CountryEducationFramework = {
  countryCode: 'ZA',
  countryName: 'South Africa',
  officialFlagEmoji: '🇿🇦',
  nationalEducationAuthority: 'Department of Basic Education (DBE) / Umalusi / SACE',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'zu', name: 'isiZulu', isOfficial: true },
    { code: 'xh', name: 'isiXhosa', isOfficial: true },
    { code: 'af', name: 'Afrikaans', isOfficial: true },
    { code: 'st', name: 'Sesotho', isOfficial: true },
    { code: 'nso', name: 'Sepedi', isOfficial: true },
    { code: 'tn', name: 'Setswana', isOfficial: true },
  ],
  timeZone: 'Africa/Johannesburg',
  currency: {
    code: 'ZAR',
    symbol: 'R',
    name: 'South African Rand',
    decimals: 2,
    formatPattern: '#,##0.00',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'QUARTERS_4',
    termsCount: 4,
    academicYearStartMonth: 'January',
    academicYearFormat: 'SINGLE_YEAR',
    defaultHolidaysWeeks: 3,
    terms: [
      { termNumber: 1, name: 'Term 1', defaultStartMonth: 'January', defaultEndMonth: 'March', weeksDuration: 10 },
      { termNumber: 2, name: 'Term 2', defaultStartMonth: 'April', defaultEndMonth: 'June', weeksDuration: 11 },
      { termNumber: 3, name: 'Term 3', defaultStartMonth: 'July', defaultEndMonth: 'September', weeksDuration: 11 },
      { termNumber: 4, name: 'Term 4', defaultStartMonth: 'October', defaultEndMonth: 'December', weeksDuration: 10 },
    ],
  },
  educationLevels: [
    {
      id: 'za-foundation',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Foundation Phase (Grade R - Grade 3)',
      typicalAgeRange: '5 - 9 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'GRADE_R', displayName: 'Grade R (Reception)', code: 'GR', standardAge: 5 },
        { gradeKey: 'GRADE_1', displayName: 'Grade 1', code: 'G1', standardAge: 6 },
        { gradeKey: 'GRADE_2', displayName: 'Grade 2', code: 'G2', standardAge: 7 },
        { gradeKey: 'GRADE_3', displayName: 'Grade 3', code: 'G3', standardAge: 8 },
      ],
    },
    {
      id: 'za-intermediate',
      levelKey: 'PRIMARY',
      displayName: 'Intermediate Phase (Grade 4 - Grade 6)',
      typicalAgeRange: '9 - 12 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'GRADE_4', displayName: 'Grade 4', code: 'G4', standardAge: 9 },
        { gradeKey: 'GRADE_5', displayName: 'Grade 5', code: 'G5', standardAge: 10 },
        { gradeKey: 'GRADE_6', displayName: 'Grade 6', code: 'G6', standardAge: 11 },
      ],
    },
    {
      id: 'za-senior-phase',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Senior Phase (Grade 7 - Grade 9 GET)',
      typicalAgeRange: '12 - 15 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'GRADE_7', displayName: 'Grade 7', code: 'G7', standardAge: 12 },
        { gradeKey: 'GRADE_8', displayName: 'Grade 8 (High School Entry)', code: 'G8', standardAge: 13 },
        { gradeKey: 'GRADE_9', displayName: 'Grade 9 (GET Certificate)', code: 'G9', standardAge: 14 },
      ],
    },
    {
      id: 'za-fet-phase',
      levelKey: 'SENIOR_SECONDARY',
      displayName: 'Further Education and Training (FET Grade 10 - Grade 12 NSC)',
      typicalAgeRange: '15 - 18 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'GRADE_10', displayName: 'Grade 10', code: 'G10', standardAge: 15 },
        { gradeKey: 'GRADE_11', displayName: 'Grade 11', code: 'G11', standardAge: 16 },
        { gradeKey: 'GRADE_12', displayName: 'Grade 12 (Matric NSC Candidate)', code: 'G12', standardAge: 17 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'za-dbe-caps',
      code: 'DBE-CAPS-ZA',
      name: 'National Curriculum Statement (NCS) CAPS',
      countryCode: 'ZA',
      type: 'STANDARDS_BASED',
      authority: 'Department of Basic Education (DBE)',
      description: 'South African national curriculum specifying content, concepts, and assessment requirements per subject and grade.',
      isNationalStandard: true,
      version: 'CAPS.v3',
      effectiveYear: 2012,
      applicableLevels: ['za-foundation', 'za-intermediate', 'za-senior-phase', 'za-fet-phase'],
      subjects: [
        { code: 'ENG-HL', name: 'English Home Language', category: 'Core', isCompulsory: true },
        { code: 'FAL-LANG', name: 'First Additional Language (Afrikaans / isiZulu / isiXhosa)', category: 'Core', isCompulsory: true },
        { code: 'MATH-CORE', name: 'Mathematics (or Mathematical Literacy)', category: 'Core', isCompulsory: true },
        { code: 'LO-ZA', name: 'Life Orientation (LO)', category: 'Core', isCompulsory: true },
        { code: 'PHY-SCI', name: 'Physical Sciences (Physics & Chemistry)', category: 'Elective', isCompulsory: false },
        { code: 'LIFE-SCI', name: 'Life Sciences (Biology)', category: 'Elective', isCompulsory: false },
        { code: 'ACC-ZA', name: 'Accounting', category: 'Elective', isCompulsory: false },
        { code: 'BUS-ZA', name: 'Business Studies', category: 'Elective', isCompulsory: false },
        { code: 'CAT-ZA', name: 'Computer Applications Technology (CAT)', category: 'Vocational', isCompulsory: false },
        { code: 'IT-ZA', name: 'Information Technology (IT Programming)', category: 'Vocational', isCompulsory: false },
        { code: 'GEO-ZA', name: 'Geography', category: 'Elective', isCompulsory: false },
        { code: 'HIST-ZA', name: 'History', category: 'Elective', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'za-dbe-7point-scale',
      name: 'South Africa DBE 7-Point Rating Scale (Levels 7 to 1)',
      scaleType: 'RATING_SCALE_7',
      description: 'Official DBE rating code scale for school reporting and National Senior Certificate (NSC) Matric pass qualification.',
      continuousAssessmentWeightPercent: 25,
      examinationWeightPercent: 75,
      supportsRubrics: true,
      scales: [
        { grade: 'Level 7', minPercentage: 80, maxPercentage: 100, points: 7, descriptor: 'Outstanding Achievement (80% - 100%)', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'Level 6', minPercentage: 70, maxPercentage: 79, points: 6, descriptor: 'Meritorious Achievement (70% - 79%)', classification: 'Meritorious', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'Level 5', minPercentage: 60, maxPercentage: 69, points: 5, descriptor: 'Substantial Achievement (60% - 69%)', classification: 'Substantial', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'Level 4', minPercentage: 50, maxPercentage: 59, points: 4, descriptor: 'Adequate Achievement (50% - 59%)', classification: 'Adequate', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'Level 3', minPercentage: 40, maxPercentage: 49, points: 3, descriptor: 'Moderate Achievement (40% - 49%)', classification: 'Moderate', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'Level 2', minPercentage: 30, maxPercentage: 39, points: 2, descriptor: 'Elementary Achievement (30% - 39%)', classification: 'Elementary', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'Level 1', minPercentage: 0, maxPercentage: 29, points: 1, descriptor: 'Not Achieved (0% - 29%)', classification: 'Not Achieved', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Subject',
    subjectsLabelPlural: 'Subjects',
    gradeLabel: 'Grade',
    termLabel: 'Term',
    headOfSchoolLabel: 'Principal',
    deputyHeadLabel: 'Deputy Principal',
    directorOfStudiesLabel: 'Head of Department (HOD Academics)',
    reportCardLabel: 'Quarterly Progress Report Card',
    nationalExamLabel: 'National Senior Certificate (NSC Matric) / ANA',
    bursarLabel: 'Finance Manager / Bursar',
  },
  paymentGateways: [
    {
      providerId: 'ozow-za',
      displayName: 'Ozow Instant EFT South Africa',
      type: 'INSTANT_EFT',
      isPopularInCountry: true,
      supportedMethods: ['Instant EFT from Capitec, FNB, Standard Bank, Absa, Nedbank'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'ZAR',
    },
    {
      providerId: 'payfast-za',
      displayName: 'PayFast South Africa (Cards, Masterpass, Debit)',
      type: 'HYBRID_GATEWAY',
      isPopularInCountry: true,
      supportedMethods: ['Visa/Mastercard', 'Instant EFT', 'Debit Card', 'SnapScan', 'Zapper'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'ZAR',
    },
    {
      providerId: 'snapscan-za',
      displayName: 'SnapScan / Zapper QR Payments',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['In-app QR scan', 'Push payment link'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'ZAR',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'za-sasams-lurits',
      systemName: 'SA-SAMS & LURITS National Learner Database',
      authorityName: 'Department of Basic Education EMIS Directorate',
      supportedFormats: ['XML', 'CSV', 'PDF'],
      complianceVersion: 'SA-SAMS-v23.1',
      samplePayloadSummary: 'Learner unit tracking records (LURITS IDs), School-Based Assessment (SBA) marks, Quarterly attendance aggregates, Educator workload statistics.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Protection of Personal Information Act, 2013 (POPIA)',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.4.0',
  lastUpdated: '2026-08-18',
};
