// ============================================================================
// COUNTRY EDUCATION PACK: TANZANIA (TZ)
// Ministry of Education, Science and Technology (MoEST) / NECTA / TIE
// ============================================================================

import { CountryEducationFramework } from '../types';

export const tanzaniaFrameworkPack: CountryEducationFramework = {
  countryCode: 'TZ',
  countryName: 'Tanzania',
  officialFlagEmoji: '🇹🇿',
  nationalEducationAuthority: 'Ministry of Education, Science and Technology (MoEST) / NECTA / TIE',
  defaultLanguage: 'Kiswahili',
  supportedLanguages: [
    { code: 'sw', name: 'Kiswahili', isOfficial: true },
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'fr', name: 'French', isOfficial: false },
  ],
  timeZone: 'Africa/Dar_es_Salaam',
  currency: {
    code: 'TZS',
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    decimals: 0,
    formatPattern: '#,##0',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'SEMESTERS_2',
    termsCount: 2,
    academicYearStartMonth: 'January',
    academicYearFormat: 'SINGLE_YEAR',
    defaultHolidaysWeeks: 4,
    terms: [
      { termNumber: 1, name: 'Muhula wa Kwanza (Term 1)', defaultStartMonth: 'January', defaultEndMonth: 'June', weeksDuration: 20 },
      { termNumber: 2, name: 'Muhula wa Pili (Term 2)', defaultStartMonth: 'July', defaultEndMonth: 'December', weeksDuration: 20 },
    ],
  },
  educationLevels: [
    {
      id: 'tz-awali',
      levelKey: 'PRE_PRIMARY',
      displayName: 'Elimu ya Awali (Pre-Primary)',
      localName: 'Elimu ya Awali',
      typicalAgeRange: '5 - 6 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'AWALI_1', displayName: 'Awali Mwaka 1', code: 'AW1', standardAge: 5 },
        { gradeKey: 'AWALI_2', displayName: 'Awali Mwaka 2', code: 'AW2', standardAge: 6 },
      ],
    },
    {
      id: 'tz-msingi',
      levelKey: 'PRIMARY',
      displayName: 'Elimu ya Msingi (Standard 1 - 7)',
      localName: 'Shule ya Msingi (PSLE)',
      typicalAgeRange: '7 - 13 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'STD_1', displayName: 'Darasa la Kwanza (Std 1)', code: 'STD1', standardAge: 7 },
        { gradeKey: 'STD_2', displayName: 'Darasa la Pili (Std 2)', code: 'STD2', standardAge: 8 },
        { gradeKey: 'STD_3', displayName: 'Darasa la Tatu (Std 3)', code: 'STD3', standardAge: 9 },
        { gradeKey: 'STD_4', displayName: 'Darasa la Nne (Std 4 SFNA)', code: 'STD4', standardAge: 10 },
        { gradeKey: 'STD_5', displayName: 'Darasa la Tano (Std 5)', code: 'STD5', standardAge: 11 },
        { gradeKey: 'STD_6', displayName: 'Darasa la Sita (Std 6)', code: 'STD6', standardAge: 12 },
        { gradeKey: 'STD_7', displayName: 'Darasa la Saba (Std 7 PSLE Candidate)', code: 'STD7', standardAge: 13 },
      ],
    },
    {
      id: 'tz-sekondari-o',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Elimu ya Sekondari (Form 1 - 4 CSEE)',
      localName: 'Kidato cha 1 - 4',
      typicalAgeRange: '14 - 17 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'FORM_1', displayName: 'Kidato cha Kwanza (Form 1)', code: 'F1', standardAge: 14 },
        { gradeKey: 'FORM_2', displayName: 'Kidato cha Pili (Form 2 FTNA)', code: 'F2', standardAge: 15 },
        { gradeKey: 'FORM_3', displayName: 'Kidato cha Tatu (Form 3)', code: 'F3', standardAge: 16 },
        { gradeKey: 'FORM_4', displayName: 'Kidato cha Nne (Form 4 CSEE Candidate)', code: 'F4', standardAge: 17 },
      ],
    },
    {
      id: 'tz-sekondari-a',
      levelKey: 'UPPER_SECONDARY',
      displayName: 'Elimu ya Sekondari ya Juu (Form 5 - 6 ACSEE)',
      localName: 'Kidato cha 5 - 6 (High School)',
      typicalAgeRange: '18 - 19 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'FORM_5', displayName: 'Kidato cha Tano (Form 5)', code: 'F5', standardAge: 18 },
        { gradeKey: 'FORM_6', displayName: 'Kidato cha Sita (Form 6 ACSEE Candidate)', code: 'F6', standardAge: 19 },
      ],
    },
    {
      id: 'tz-veta',
      levelKey: 'TECHNICAL_VOCATIONAL',
      displayName: 'Mafunzo ya Ufundi Stadi (VETA)',
      localName: 'VETA Vocational Training',
      typicalAgeRange: '17+ Years',
      sortOrder: 5,
      grades: [
        { gradeKey: 'VETA_1', displayName: 'VETA Level I Certificate', code: 'VL1', standardAge: 18 },
        { gradeKey: 'VETA_2', displayName: 'VETA Level II Diploma', code: 'VL2', standardAge: 19 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'tz-tie-csee-sec',
      code: 'TIE-CSEE-NAT',
      name: 'Tanzania National Secondary Curriculum (TIE / NECTA CSEE)',
      countryCode: 'TZ',
      type: 'TRADITIONAL_SUBJECT_BASED',
      authority: 'Tanzania Institute of Education (TIE)',
      description: 'National secondary curriculum preparing learners for the Certificate of Secondary Education Examination (CSEE).',
      isNationalStandard: true,
      version: '2023.v2',
      effectiveYear: 2019,
      applicableLevels: ['tz-sekondari-o'],
      subjects: [
        { code: 'KISW', name: 'Kiswahili', category: 'Core', isCompulsory: true },
        { code: 'ENG', name: 'English Language', category: 'Core', isCompulsory: true },
        { code: 'B-MATH', name: 'Basic Mathematics', category: 'Core', isCompulsory: true },
        { code: 'BIO', name: 'Biology', category: 'Core', isCompulsory: true },
        { code: 'CIV', name: 'Civics', category: 'Core', isCompulsory: true },
        { code: 'HIST', name: 'History', category: 'Core', isCompulsory: true },
        { code: 'GEO', name: 'Geography', category: 'Core', isCompulsory: true },
        { code: 'PHY', name: 'Physics', category: 'Elective', isCompulsory: false },
        { code: 'CHEM', name: 'Chemistry', category: 'Elective', isCompulsory: false },
        { code: 'COMM', name: 'Commerce & Bookkeeping', category: 'Vocational', isCompulsory: false },
        { code: 'ICS', name: 'Information and Computer Studies (ICS)', category: 'Vocational', isCompulsory: false },
        { code: 'AGR-TZ', name: 'Agriculture', category: 'Vocational', isCompulsory: false },
      ],
    },
    {
      id: 'tz-tie-primary-msingi',
      code: 'TIE-MSINGI-CBC',
      name: 'Mtaala wa Elimu ya Msingi (TIE Competence-Based Primary)',
      countryCode: 'TZ',
      type: 'COMPETENCY_BASED',
      authority: 'Taasisi ya Elimu Tanzania (TET)',
      description: 'Curriculum focusing on Kiswahili, English, Mathematics, Science, and Social Studies fundamentals.',
      isNationalStandard: true,
      version: '2021.v1',
      effectiveYear: 2018,
      applicableLevels: ['tz-msingi'],
      subjects: [
        { code: 'KISW-M', name: 'Kiswahili', category: 'Core', isCompulsory: true },
        { code: 'ENG-M', name: 'English', category: 'Core', isCompulsory: true },
        { code: 'HIS-M', name: 'Hisabati (Mathematics)', category: 'Core', isCompulsory: true },
        { code: 'SAY-M', name: 'Sayansi na Teknolojia (Science)', category: 'Core', isCompulsory: true },
        { code: 'MAAR-M', name: 'Maarifa ya Jamii (Social Studies)', category: 'Core', isCompulsory: true },
        { code: 'UZAL-M', name: 'Uraia na Maadili (Civic & Moral)', category: 'Core', isCompulsory: true },
        { code: 'SANAA-M', name: 'Sanaa na Michezo (Sports & Arts)', category: 'Co-Curricular', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'tz-necta-csee-scale',
      name: 'NECTA National Secondary Grading Scale (A to F & Divisions I - IV)',
      scaleType: 'LETTER_GRADES_5',
      description: 'National examination grading scale governed by NECTA with points calculation for Division 1 to 4 and Division 0.',
      continuousAssessmentWeightPercent: 30,
      examinationWeightPercent: 70,
      supportsRubrics: false,
      divisionSystem: {
        enabled: true,
        name: 'NECTA Division Classification (Best 7 Subjects)',
        rules: [
          { division: 'Division I', minPoints: 7, maxPoints: 17, description: 'Daraja la Kwanza (Distinction standing)' },
          { division: 'Division II', minPoints: 18, maxPoints: 21, description: 'Daraja la Pili (Very good performance)' },
          { division: 'Division III', minPoints: 22, maxPoints: 25, description: 'Daraja la Tatu (Good secondary pass)' },
          { division: 'Division IV', minPoints: 26, maxPoints: 33, description: 'Daraja la Nne (Satisfactory minimum pass)' },
          { division: 'Division 0', minPoints: 34, maxPoints: 35, description: 'Daraja la Sifuri (Fail / Not achieved)' },
        ],
      },
      scales: [
        { grade: 'A', minPercentage: 75, maxPercentage: 100, points: 1, descriptor: 'Bora Sana (Excellent / Distinction)', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'B', minPercentage: 65, maxPercentage: 74, points: 2, descriptor: 'Vizuri Sana (Very Good)', classification: 'Very Good', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'C', minPercentage: 45, maxPercentage: 64, points: 3, descriptor: 'Vizuri (Good / Credit)', classification: 'Good', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'D', minPercentage: 30, maxPercentage: 44, points: 4, descriptor: 'Hafifu (Pass / Weak)', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'F', minPercentage: 0, maxPercentage: 29, points: 5, descriptor: 'Feli (Fail)', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Somo (Subject)',
    subjectsLabelPlural: 'Masomo',
    gradeLabel: 'Darasa / Kidato',
    termLabel: 'Muhula (Semester)',
    headOfSchoolLabel: 'Mkuu wa Shule (Head of School)',
    deputyHeadLabel: 'Makamu Mkuu wa Shule',
    directorOfStudiesLabel: 'Mwalimu Mkuu wa Taaluma',
    reportCardLabel: 'Ripoti ya Maendeleo ya Mwanafunzi',
    nationalExamLabel: 'Mtihani wa Taifa wa NECTA (PSLE/CSEE/ACSEE)',
    bursarLabel: 'Mhasibu wa Shule',
  },
  paymentGateways: [
    {
      providerId: 'vodacom-mpesa-tz',
      displayName: 'Vodacom M-Pesa Tanzania (Lipa kwa M-Pesa)',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['M-Pesa STK Push', 'Lipa kwa Simu / Merchant No'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'TZS',
    },
    {
      providerId: 'tigo-pesa-tz',
      displayName: 'Tigo Pesa / Mixx by Yas',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Tigo Pesa Push', 'Masterpass QR'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'TZS',
    },
    {
      providerId: 'airtel-money-tz',
      displayName: 'Airtel Money Tanzania',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Airtel Money STK'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'TZS',
    },
    {
      providerId: 'selcom-tz',
      displayName: 'Selcom Paytech / NMB / CRDB Gateway',
      type: 'HYBRID_GATEWAY',
      isPopularInCountry: true,
      supportedMethods: ['Selcom Control Number', 'Bank Card', 'All Mobile Wallets'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'TZS',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'tz-bemis-census',
      systemName: 'Basic Education Management Information System (BEMIS Tanzania)',
      authorityName: 'Tamisemi / MoEST Statistics Directorate',
      supportedFormats: ['XML', 'CSV', 'JSON', 'PDF'],
      complianceVersion: 'BEMIS-v4.0',
      samplePayloadSummary: 'Wanafunzi waliosajiliwa, matokeo ya mitihani ya ndani, miundombinu ya shule, orodha ya walimu.',
    },
    {
      adapterId: 'tz-necta-ereg',
      systemName: 'NECTA Online Candidate Registration & CA Portal',
      authorityName: 'National Examinations Council of Tanzania',
      supportedFormats: ['CSV', 'XML', 'PDF'],
      complianceVersion: 'NECTA-PREG-2025',
      samplePayloadSummary: 'Alama za Upimaji Endelevu (Continuous Assessment), picha za wanafunzi, namba za watahiniwa.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Personal Data Protection Act, 2022 (PDPC Tanzania)',
    dataResidencyDefaultRegion: 'africa-south1',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 10,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.3.0',
  lastUpdated: '2026-08-18',
};
