// ============================================================================
// COUNTRY EDUCATION PACK: UGANDA (UG)
// Ministry of Education and Sports (MoES) / UNEB / NCDC
// ============================================================================

import { CountryEducationFramework } from '../types';

export const ugandaFrameworkPack: CountryEducationFramework = {
  countryCode: 'UG',
  countryName: 'Uganda',
  officialFlagEmoji: '🇺🇬',
  nationalEducationAuthority: 'Ministry of Education and Sports (MoES) / UNEB / NCDC',
  defaultLanguage: 'English',
  supportedLanguages: [
    { code: 'en', name: 'English', isOfficial: true },
    { code: 'lg', name: 'Luganda', isOfficial: false },
    { code: 'nyn', name: 'Runyankole/Rukiga', isOfficial: false },
    { code: 'luo', name: 'Luo/Acholi', isOfficial: false },
    { code: 'teo', name: 'Ateso', isOfficial: false },
    { code: 'sw', name: 'Kiswahili', isOfficial: true },
  ],
  timeZone: 'Africa/Kampala',
  currency: {
    code: 'UGX',
    symbol: 'USh',
    name: 'Ugandan Shilling',
    decimals: 0,
    formatPattern: '#,##0',
    symbolPosition: 'PREFIX',
  },
  calendar: {
    periodType: 'TERMS_3',
    termsCount: 3,
    academicYearStartMonth: 'January',
    academicYearFormat: 'SINGLE_YEAR',
    defaultHolidaysWeeks: 4,
    terms: [
      { termNumber: 1, name: 'Term I', defaultStartMonth: 'February', defaultEndMonth: 'May', weeksDuration: 13 },
      { termNumber: 2, name: 'Term II', defaultStartMonth: 'May', defaultEndMonth: 'August', weeksDuration: 13 },
      { termNumber: 3, name: 'Term III', defaultStartMonth: 'September', defaultEndMonth: 'December', weeksDuration: 13 },
    ],
  },
  educationLevels: [
    {
      id: 'ug-ecd',
      levelKey: 'EARLY_CHILDHOOD',
      displayName: 'Early Childhood Development (Nursery)',
      typicalAgeRange: '3 - 5 Years',
      sortOrder: 1,
      grades: [
        { gradeKey: 'BABY', displayName: 'Baby Class', code: 'BC', standardAge: 3 },
        { gradeKey: 'MIDDLE', displayName: 'Middle Class', code: 'MC', standardAge: 4 },
        { gradeKey: 'TOP', displayName: 'Top Class', code: 'TC', standardAge: 5 },
      ],
    },
    {
      id: 'ug-pri',
      levelKey: 'PRIMARY',
      displayName: 'Primary Education (PLE)',
      typicalAgeRange: '6 - 12 Years',
      sortOrder: 2,
      grades: [
        { gradeKey: 'P1', displayName: 'Primary 1', code: 'P1', standardAge: 6 },
        { gradeKey: 'P2', displayName: 'Primary 2', code: 'P2', standardAge: 7 },
        { gradeKey: 'P3', displayName: 'Primary 3', code: 'P3', standardAge: 8 },
        { gradeKey: 'P4', displayName: 'Primary 4', code: 'P4', standardAge: 9 },
        { gradeKey: 'P5', displayName: 'Primary 5', code: 'P5', standardAge: 10 },
        { gradeKey: 'P6', displayName: 'Primary 6', code: 'P6', standardAge: 11 },
        { gradeKey: 'P7', displayName: 'Primary 7 (Candidate)', code: 'P7', standardAge: 12 },
      ],
    },
    {
      id: 'ug-lower-sec',
      levelKey: 'LOWER_SECONDARY',
      displayName: 'Lower Secondary (NCDC CBC / UCE)',
      typicalAgeRange: '13 - 16 Years',
      sortOrder: 3,
      grades: [
        { gradeKey: 'S1', displayName: 'Senior 1', code: 'S1', standardAge: 13 },
        { gradeKey: 'S2', displayName: 'Senior 2', code: 'S2', standardAge: 14 },
        { gradeKey: 'S3', displayName: 'Senior 3', code: 'S3', standardAge: 15 },
        { gradeKey: 'S4', displayName: 'Senior 4 (UCE Candidate)', code: 'S4', standardAge: 16 },
      ],
    },
    {
      id: 'ug-upper-sec',
      levelKey: 'UPPER_SECONDARY',
      displayName: 'Upper Secondary / High School (UACE)',
      typicalAgeRange: '17 - 18 Years',
      sortOrder: 4,
      grades: [
        { gradeKey: 'S5', displayName: 'Senior 5', code: 'S5', standardAge: 17 },
        { gradeKey: 'S6', displayName: 'Senior 6 (UACE Candidate)', code: 'S6', standardAge: 18 },
      ],
    },
    {
      id: 'ug-tvet',
      levelKey: 'TECHNICAL_VOCATIONAL',
      displayName: 'Technical and Vocational (BTVET / DIT)',
      typicalAgeRange: '16+ Years',
      sortOrder: 5,
      grades: [
        { gradeKey: 'YEAR_1', displayName: 'Year 1 Certificate', code: 'Y1', standardAge: 17 },
        { gradeKey: 'YEAR_2', displayName: 'Year 2 Diploma', code: 'Y2', standardAge: 18 },
      ],
    },
  ],
  availableCurricula: [
    {
      id: 'ug-ncdc-cbc-lower-sec',
      code: 'NCDC-CBC-2020',
      name: 'NCDC Competency-Based Lower Secondary Curriculum',
      countryCode: 'UG',
      type: 'COMPETENCY_BASED',
      authority: 'National Curriculum Development Centre (NCDC)',
      description: 'Learner-centred, competency-based curriculum emphasizing 21st-century skills, continuous project work (20%), and summative assessment (80%).',
      isNationalStandard: true,
      version: '2020.v2',
      effectiveYear: 2020,
      applicableLevels: ['ug-lower-sec'],
      subjects: [
        { code: 'ENG', name: 'English Language', category: 'Core', isCompulsory: true },
        { code: 'MTH', name: 'Mathematics', category: 'Core', isCompulsory: true },
        { code: 'PHY', name: 'Physics', category: 'Core', isCompulsory: true },
        { code: 'CHE', name: 'Chemistry', category: 'Core', isCompulsory: true },
        { code: 'BIO', name: 'Biology', category: 'Core', isCompulsory: true },
        { code: 'GEO', name: 'Geography', category: 'Core', isCompulsory: true },
        { code: 'HIS', name: 'History & Political Education', category: 'Core', isCompulsory: true },
        { code: 'ICT', name: 'Information and Communications Technology', category: 'Core', isCompulsory: true },
        { code: 'CRE', name: 'Christian Religious Education', category: 'Elective', isCompulsory: false },
        { code: 'IRE', name: 'Islamic Religious Education', category: 'Elective', isCompulsory: false },
        { code: 'AGR', name: 'Agriculture', category: 'Vocational', isCompulsory: false },
        { code: 'ENT', name: 'Entrepreneurship', category: 'Vocational', isCompulsory: false },
        { code: 'ART', name: 'Art and Design', category: 'Co-Curricular', isCompulsory: false },
        { code: 'LUG', name: 'Luganda Local Language', category: 'Elective', isCompulsory: false },
      ],
    },
    {
      id: 'ug-uneb-ple-primary',
      code: 'UNEB-PLE-PRIM',
      name: 'Uganda National Primary Curriculum (PLE)',
      countryCode: 'UG',
      type: 'TRADITIONAL_SUBJECT_BASED',
      authority: 'Ministry of Education and Sports / UNEB',
      description: 'Primary thematic and subject curriculum preparing learners for the Primary Leaving Examination.',
      isNationalStandard: true,
      version: '2016.v1',
      effectiveYear: 2016,
      applicableLevels: ['ug-pri'],
      subjects: [
        { code: 'ENG-P', name: 'English', category: 'Core', isCompulsory: true },
        { code: 'MTC-P', name: 'Mathematics', category: 'Core', isCompulsory: true },
        { code: 'SCI-P', name: 'Integrated Science', category: 'Core', isCompulsory: true },
        { code: 'SST-P', name: 'Social Studies & Religious Education', category: 'Core', isCompulsory: true },
      ],
    },
    {
      id: 'ug-uneb-uace-upper',
      code: 'UNEB-UACE-UPPER',
      name: 'Uganda Advanced Certificate of Education (UACE)',
      countryCode: 'UG',
      type: 'TRADITIONAL_SUBJECT_BASED',
      authority: 'Uganda National Examinations Board (UNEB)',
      description: 'Advanced Level principal subject combinations (PCB, PCM, BCM, HEG, DEG) with Subsidiary ICT and General Paper.',
      isNationalStandard: true,
      version: '2018.v1',
      effectiveYear: 2018,
      applicableLevels: ['ug-upper-sec'],
      subjects: [
        { code: 'GP', name: 'General Paper', category: 'Core', isCompulsory: true },
        { code: 'SUB-ICT', name: 'Subsidiary ICT', category: 'Core', isCompulsory: true },
        { code: 'PHY-A', name: 'Physics (Principal)', category: 'Elective', isCompulsory: false },
        { code: 'CHE-A', name: 'Chemistry (Principal)', category: 'Elective', isCompulsory: false },
        { code: 'BIO-A', name: 'Biology (Principal)', category: 'Elective', isCompulsory: false },
        { code: 'MTH-A', name: 'Pure Mathematics (Principal)', category: 'Elective', isCompulsory: false },
        { code: 'ECO-A', name: 'Economics (Principal)', category: 'Elective', isCompulsory: false },
        { code: 'GEO-A', name: 'Geography (Principal)', category: 'Elective', isCompulsory: false },
      ],
    },
  ],
  gradingSystems: [
    {
      id: 'ug-ncdc-cbc-levels',
      name: 'Uganda NCDC Competency Descriptors (Scale 1.0 - 3.0)',
      scaleType: 'COMPETENCY_DESCRIPTORS_3',
      description: 'Scores between 1.0 and 3.0 representing Basic, Moderate, and Outstanding competence achievement.',
      continuousAssessmentWeightPercent: 20,
      examinationWeightPercent: 80,
      supportsRubrics: true,
      scales: [
        { grade: '3.0 (Outstanding)', minPercentage: 75, maxPercentage: 100, points: 3, descriptor: 'Outstanding Competence (Produces exceptional high-quality innovative output)', classification: 'Outstanding', colorHex: '#10B981', isPassingGrade: true },
        { grade: '2.0 (Moderate)', minPercentage: 50, maxPercentage: 74, points: 2, descriptor: 'Moderate Competence (Meets required core learning outcomes independently)', classification: 'Moderate', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: '1.0 (Basic)', minPercentage: 0, maxPercentage: 49, points: 1, descriptor: 'Basic Competence (Demonstrates partial comprehension; requires teacher remediation)', classification: 'Basic', colorHex: '#F59E0B', isPassingGrade: false },
      ],
    },
    {
      id: 'ug-uneb-aggregates-9',
      name: 'Uganda UNEB 9-Point Aggregate & Division System (D1 - F9)',
      scaleType: 'NUMERIC_AGGREGATES_9',
      description: 'Standard UNEB national examination aggregate points scale with Division I, II, III, IV, and U classification.',
      continuousAssessmentWeightPercent: 0,
      examinationWeightPercent: 100,
      supportsRubrics: false,
      divisionSystem: {
        enabled: true,
        name: 'UNEB Division Classification',
        rules: [
          { division: 'Division I', minPoints: 8, maxPoints: 32, description: 'First Class Distinction (Top academic standing)' },
          { division: 'Division II', minPoints: 33, maxPoints: 45, description: 'Second Class Credit (Strong academic pass)' },
          { division: 'Division III', minPoints: 46, maxPoints: 58, description: 'Third Class Pass (Satisfactory achievement)' },
          { division: 'Division IV', minPoints: 59, maxPoints: 68, description: 'Fourth Class Pass (Marginal pass)' },
          { division: 'Division 9 / U', minPoints: 69, maxPoints: 72, description: 'Ungraded (Failed to attain minimum standard)' },
        ],
      },
      scales: [
        { grade: 'D1', minPercentage: 80, maxPercentage: 100, points: 1, descriptor: 'Distinction 1', classification: 'Distinction', colorHex: '#059669', isPassingGrade: true },
        { grade: 'D2', minPercentage: 75, maxPercentage: 79, points: 2, descriptor: 'Distinction 2', classification: 'Distinction', colorHex: '#10B981', isPassingGrade: true },
        { grade: 'C3', minPercentage: 70, maxPercentage: 74, points: 3, descriptor: 'Credit 3', classification: 'Credit', colorHex: '#2563EB', isPassingGrade: true },
        { grade: 'C4', minPercentage: 65, maxPercentage: 69, points: 4, descriptor: 'Credit 4', classification: 'Credit', colorHex: '#3B82F6', isPassingGrade: true },
        { grade: 'C5', minPercentage: 60, maxPercentage: 64, points: 5, descriptor: 'Credit 5', classification: 'Credit', colorHex: '#60A5FA', isPassingGrade: true },
        { grade: 'C6', minPercentage: 55, maxPercentage: 59, points: 6, descriptor: 'Credit 6', classification: 'Credit', colorHex: '#93C5FD', isPassingGrade: true },
        { grade: 'P7', minPercentage: 50, maxPercentage: 54, points: 7, descriptor: 'Pass 7', classification: 'Pass', colorHex: '#F59E0B', isPassingGrade: true },
        { grade: 'P8', minPercentage: 45, maxPercentage: 49, points: 8, descriptor: 'Pass 8', classification: 'Pass', colorHex: '#FBBF24', isPassingGrade: true },
        { grade: 'F9', minPercentage: 0, maxPercentage: 44, points: 9, descriptor: 'Fail 9', classification: 'Fail', colorHex: '#EF4444', isPassingGrade: false },
      ],
    },
  ],
  terminology: {
    subjectLabel: 'Subject',
    subjectsLabelPlural: 'Subjects',
    gradeLabel: 'Class',
    termLabel: 'Term',
    headOfSchoolLabel: 'Headteacher',
    deputyHeadLabel: 'Deputy Headteacher',
    directorOfStudiesLabel: 'Director of Studies (DOS)',
    reportCardLabel: 'End of Term Report Card',
    nationalExamLabel: 'UNEB Examination (PLE/UCE/UACE)',
    bursarLabel: 'Bursar',
  },
  paymentGateways: [
    {
      providerId: 'pesapal-ug',
      displayName: 'Pesapal Uganda (Cards, MTN, Airtel)',
      type: 'PESAPAL',
      isPopularInCountry: true,
      supportedMethods: ['MTN Mobile Money', 'Airtel Money', 'Visa/Mastercard', 'Bank Transfer'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'UGX',
    },
    {
      providerId: 'mtn-momo-ug',
      displayName: 'MTN Mobile Money Direct API',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['MTN MoMo STK Push', 'Merchant Code'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'UGX',
    },
    {
      providerId: 'airtel-money-ug',
      displayName: 'Airtel Money Uganda STK',
      type: 'MOBILE_MONEY',
      isPopularInCountry: true,
      supportedMethods: ['Airtel Money STK Push'],
      integrationStatus: 'ACTIVE',
      currencyCode: 'UGX',
    },
    {
      providerId: 'centenary-schoolpay-ug',
      displayName: 'SchoolPay / Centenary Bank System',
      type: 'CARD_BANK',
      isPopularInCountry: true,
      supportedMethods: ['Student Registration PayCode', 'Bank Branch Deposit'],
      integrationStatus: 'AVAILABLE',
      currencyCode: 'UGX',
    },
  ],
  governmentReporting: [
    {
      adapterId: 'ug-moes-emis',
      systemName: 'Uganda Ministry of Education EMIS Portal',
      authorityName: 'MoES Statistics Department',
      supportedFormats: ['XML', 'JSON', 'CSV', 'PDF'],
      complianceVersion: 'EMIS-UG-2025.2',
      samplePayloadSummary: 'Annual school census dataset containing learner enrollment, teacher deployment, infrastructure audit, and PLE/UCE candidate registration counts.',
    },
    {
      adapterId: 'ug-uneb-e-reg',
      systemName: 'UNEB e-Registration & Candidate Verification Portal',
      authorityName: 'Uganda National Examinations Board',
      supportedFormats: ['CSV', 'XML', 'PDF'],
      complianceVersion: 'UNEB-EREG-v4',
      samplePayloadSummary: 'Candidate index numbers, continuous assessment scores (20% NCDC), passport photos, subject selection verification sheets.',
    },
  ],
  dataPrivacyPolicy: {
    legislationName: 'Data Protection and Privacy Act, 2019 (Uganda)',
    dataResidencyDefaultRegion: 'africa-south1 (or local school server)',
    parentalConsentAgeThreshold: 18,
    dataRetentionYears: 7,
    allowCrossBorderAnonymizedData: true,
    studentPIIRestrictionLevel: 'STRICT',
  },
  packageVersion: '2.4.0',
  lastUpdated: '2026-08-18',
};
