import React, { useState, useEffect } from 'react';
import {
  AlertTriangle,
  ShieldCheck,
  Users,
  Search,
  Filter,
  CheckCircle2,
  HelpCircle,
  Sparkles,
  ArrowRight,
  TrendingDown,
  TrendingUp,
  Clock,
  PhoneCall,
  UserCheck,
  BookOpen,
  DollarSign,
  FileSpreadsheet,
} from 'lucide-react';
import { v8IntelligenceApi } from '../services/v8IntelligenceApi';
import type { StudentSuccessPrediction, RiskDetectionAlert } from '../types';

export const StudentSuccessIntelligencePage: React.FC = () => {
  const [predictions, setPredictions] = useState<StudentSuccessPrediction[]>([]);
  const [riskAlerts, setRiskAlerts] = useState<RiskDetectionAlert[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRiskLevel, setSelectedRiskLevel] = useState('All Risk Levels');
  const [selectedCategory, setSelectedCategory] = useState('All Categories');
  const [selectedStudent, setSelectedStudent] = useState<StudentSuccessPrediction | null>(null);
  const [actionNotes, setActionNotes] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    const loadedPreds = await v8IntelligenceApi.getStudentPredictions();
    const loadedAlerts = await v8IntelligenceApi.getRiskDetectionAlerts();
    setPredictions(loadedPreds);
    setRiskAlerts(loadedAlerts);
    if (loadedPreds.length > 0 && !selectedStudent) {
      setSelectedStudent(loadedPreds[0]);
    }
    setLoading(false);
  };

  const handleActionToggle = async (studentId: string, currentState: boolean) => {
    await v8IntelligenceApi.updateStudentPredictionAction(studentId, !currentState, actionNotes);
    loadData();
  };

  const handleInitiateIntervention = async (actionTitle: string) => {
    if (!selectedStudent) return;
    const updatedNote = `Intervention Workflow Initiated: "${actionTitle}" on ${new Date().toLocaleDateString()}`;
    await v8IntelligenceApi.updateStudentPredictionAction(selectedStudent.id, true, updatedNote);
    await loadData();
  };

  const filteredPredictions = predictions.filter((p) => {
    const matchesSearch =
      p.studentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.className.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.studentId.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesLevel =
      selectedRiskLevel === 'All Risk Levels' || p.riskLevel === selectedRiskLevel;
    const matchesCat =
      selectedCategory === 'All Categories' || p.riskCategory === selectedCategory;
    return matchesSearch && matchesLevel && matchesCat;
  });

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6 text-slate-100">
      {/* Mandatory Human-In-The-Loop Safeguard Banner */}
      <div className="p-4 rounded-2xl bg-amber-950/40 border border-amber-800/60 flex items-start gap-3 shadow-lg">
        <ShieldCheck className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h2 className="text-xs font-bold text-amber-300 uppercase tracking-wider">
            Mandatory Explainable AI Safeguard Policy
          </h2>
          <p className="text-xs text-slate-300">
            Predictions generated by SchoolSoul V8 are assistive decision-support indicators based on statistical patterns from Vision 1–7 data. <strong className="text-white">AI predictions never automatically trigger disciplinary, academic, or financial decisions.</strong> All recommendations must be validated by authorized teachers or school leaders.
          </p>
        </div>
      </div>

      {/* Header Banner */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 bg-slate-900/90 border border-slate-800 p-6 rounded-2xl shadow-xl">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-rose-500/10 text-rose-400 border border-rose-500/20 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" /> Predictive Analytics Engine
            </span>
            <span className="text-xs text-slate-400">Early Warning System</span>
          </div>
          <h1 className="text-2xl font-black tracking-tight text-white flex items-center gap-2">
            Student Success & Risk Intelligence
          </h1>
          <p className="text-xs text-slate-400 max-w-2xl">
            Detect attendance decline, academic slips, welfare concerns, and fee risks early with weighted confidence scores and structured intervention workflows.
          </p>
        </div>

        {/* Quick Risk Stats */}
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-center">
            <span className="text-[10px] text-slate-400 block">Critical Risks</span>
            <span className="text-lg font-black text-rose-400">
              {predictions.filter((p) => p.riskLevel === 'Critical').length}
            </span>
          </div>
          <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-center">
            <span className="text-[10px] text-slate-400 block">High Risks</span>
            <span className="text-lg font-black text-amber-400">
              {predictions.filter((p) => p.riskLevel === 'High').length}
            </span>
          </div>
          <div className="p-3 rounded-xl bg-slate-950 border border-slate-800 text-center">
            <span className="text-[10px] text-slate-400 block">High Growth</span>
            <span className="text-lg font-black text-emerald-400">
              {predictions.filter((p) => p.riskLevel === 'Low').length}
            </span>
          </div>
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="p-4 rounded-2xl bg-slate-900/80 border border-slate-800 flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-3 flex-1">
          <div className="relative flex-1 min-w-[220px]">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search student by name, ID, or class..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-4 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500"
            />
          </div>

          <select
            value={selectedRiskLevel}
            onChange={(e) => setSelectedRiskLevel(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white cursor-pointer focus:outline-none"
          >
            <option value="All Risk Levels">All Risk Levels</option>
            <option value="Critical">Critical Risk</option>
            <option value="High">High Risk</option>
            <option value="Moderate">Moderate Risk</option>
            <option value="Low">Low Risk / High Growth</option>
          </select>

          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-white cursor-pointer focus:outline-none"
          >
            <option value="All Categories">All Categories</option>
            <option value="Attendance">Attendance Risk</option>
            <option value="Academic">Academic Decline</option>
            <option value="Multifactorial">Multifactorial</option>
            <option value="Welfare">Welfare Concerns</option>
            <option value="Financial">Financial Default</option>
          </select>
        </div>
      </div>

      {/* Main Grid: Student Roster (Left) & Deep Student Risk Analysis (Right) */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Student Roster List */}
        <div className="lg:col-span-1 space-y-3">
          <h2 className="text-sm font-bold text-slate-300 flex items-center justify-between">
            <span>Flagged Student Cohorts</span>
            <span className="text-xs text-slate-500 font-mono">{filteredPredictions.length} Records</span>
          </h2>

          <div className="space-y-2.5 max-h-[600px] overflow-y-auto pr-1">
            {filteredPredictions.map((pred) => (
              <div
                key={pred.id}
                onClick={() => setSelectedStudent(pred)}
                className={`p-4 rounded-xl border transition cursor-pointer space-y-2 ${
                  selectedStudent?.id === pred.id
                    ? 'bg-blue-950/40 border-blue-600 shadow-md'
                    : 'bg-slate-900/80 border-slate-800 hover:border-slate-700'
                }`}
              >
                <div className="flex items-center justify-between">
                  <div className="font-bold text-white text-xs">{pred.studentName}</div>
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      pred.riskLevel === 'Critical'
                        ? 'bg-rose-500/10 text-rose-400 border border-rose-500/20'
                        : pred.riskLevel === 'High'
                        ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                        : pred.riskLevel === 'Moderate'
                        ? 'bg-blue-500/10 text-blue-400 border border-blue-500/20'
                        : 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                    }`}
                  >
                    {pred.riskLevel} ({pred.overallRiskScore}%)
                  </span>
                </div>

                <div className="flex items-center justify-between text-[11px] text-slate-400">
                  <span>
                    {pred.className} {pred.classStream && `(${pred.classStream})`}
                  </span>
                  <span className="font-mono text-purple-300">{pred.confidenceScore}% Confidence</span>
                </div>

                <div className="text-[10px] text-slate-500 truncate">
                  Primary Vector: <span className="text-slate-300 font-semibold">{pred.riskCategory}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Selected Student Risk Profile Detail */}
        <div className="lg:col-span-2">
          {selectedStudent ? (
            <div className="p-6 rounded-2xl bg-slate-900/90 border border-slate-800 space-y-6 shadow-xl">
              {/* Profile Top Bar */}
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs text-blue-400">{selectedStudent.studentId}</span>
                    <span className="text-slate-600">•</span>
                    <span className="text-xs text-slate-300">
                      {selectedStudent.className} {selectedStudent.classStream && `(${selectedStudent.classStream})`}
                    </span>
                  </div>
                  <h2 className="text-xl font-extrabold text-white">{selectedStudent.studentName}</h2>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <span className="text-[10px] text-slate-400 block uppercase font-bold">AI Model Confidence</span>
                    <span className="text-lg font-black text-purple-400 font-mono">
                      {selectedStudent.confidenceScore}%
                    </span>
                  </div>
                  <div className="p-2.5 rounded-xl bg-slate-950 border border-slate-800 text-center min-w-[90px]">
                    <span className="text-[10px] text-slate-400 block uppercase font-bold">Risk Score</span>
                    <span
                      className={`text-lg font-black font-mono ${
                        selectedStudent.overallRiskScore > 75
                          ? 'text-rose-400'
                          : selectedStudent.overallRiskScore > 50
                          ? 'text-amber-400'
                          : 'text-emerald-400'
                      }`}
                    >
                      {selectedStudent.overallRiskScore} / 100
                    </span>
                  </div>
                </div>
              </div>

              {/* Contributing Factors Breakdown with Weights */}
              <div className="space-y-3">
                <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                  <Filter className="w-3.5 h-3.5 text-blue-400" /> Key Contributing Factors & Weighting
                </h3>

                <div className="space-y-2.5">
                  {selectedStudent.contributingFactors.map((factor, idx) => (
                    <div key={idx} className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
                      <div className="flex items-center justify-between text-xs font-bold">
                        <span className="text-white">{factor.factor}</span>
                        <span className="font-mono text-blue-400">{factor.weight}% Weight</span>
                      </div>
                      <p className="text-xs text-slate-400">{factor.detail}</p>
                      <div className="w-full bg-slate-900 h-1.5 rounded-full overflow-hidden">
                        <div
                          className="bg-blue-500 h-full rounded-full"
                          style={{ width: `${factor.weight}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Recommended Action Interventions */}
              <div className="space-y-3">
                <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-purple-400" /> Recommended Staff Interventions
                </h3>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {selectedStudent.suggestedActions.map((action, idx) => (
                    <div
                      key={idx}
                      className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 space-y-2 flex flex-col justify-between"
                    >
                      <div className="space-y-1">
                        <div className="flex items-center justify-between">
                          <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-500/10 text-purple-300 border border-purple-500/20">
                            {action.type}
                          </span>
                          <span
                            className={`text-[10px] font-bold ${
                              action.priority === 'High' ? 'text-rose-400' : 'text-slate-400'
                            }`}
                          >
                            {action.priority} Priority
                          </span>
                        </div>
                        <p className="text-xs font-semibold text-white pt-1">{action.title}</p>
                      </div>

                      <button
                        type="button"
                        onClick={() => handleInitiateIntervention(action.title)}
                        className="mt-2 py-1.5 px-3 rounded-lg bg-slate-900 hover:bg-slate-800 text-xs font-bold text-blue-300 border border-slate-800 flex items-center justify-center gap-1.5 transition cursor-pointer"
                      >
                        Initiate Intervention <ArrowRight className="w-3 h-3" />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              {/* Intervention Status & Staff Action Log */}
              <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-white flex items-center gap-2">
                    <UserCheck className="w-4 h-4 text-emerald-400" /> Action & Resolution Status
                  </span>
                  <button
                    onClick={() => handleActionToggle(selectedStudent.id, !!selectedStudent.actionTaken)}
                    className={`px-3 py-1.5 rounded-lg text-xs font-bold transition cursor-pointer flex items-center gap-1.5 ${
                      selectedStudent.actionTaken
                        ? 'bg-emerald-600 text-white'
                        : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                    }`}
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    {selectedStudent.actionTaken ? 'Action Verified' : 'Mark Action Completed'}
                  </button>
                </div>

                {selectedStudent.notes && (
                  <p className="text-xs text-slate-400 bg-slate-900 p-2.5 rounded-lg border border-slate-800 italic">
                    Note: {selectedStudent.notes}
                  </p>
                )}
              </div>
            </div>
          ) : (
            <div className="p-12 rounded-2xl bg-slate-900/90 border border-slate-800 text-center text-slate-500 space-y-2">
              <Users className="w-8 h-8 mx-auto text-slate-600" />
              <p className="text-xs">Select a student from the left roster to view predictive risk factors and actions.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
