// ============================================================================
// SCHOOLSOUL GLOBAL COUNTRIES MASTER DIRECTORY
// Standardized Global ISO Country Registry & Framework Mapping
// ============================================================================

import { SupportedCountryCode } from './types';

export interface GlobalCountryInfo {
  code: string; // ISO 3166-1 alpha-2 e.g. 'UG', 'KE', 'US', 'GB'
  iso3: string; // ISO 3166-1 alpha-3 e.g. 'UGA', 'KEN', 'USA', 'GBR'
  name: string;
  officialName: string;
  flagEmoji: string;
  defaultCurrency: string;
  currencySymbol: string;
  defaultTimezone: string;
  defaultLanguage: string;
  supportedLanguages: string[];
  defaultDateFormat: string;
  phonePrefix: string;
  frameworkPackCode: SupportedCountryCode; // Map to pack or fallback to 'INTL' or regional pack
  region: 'East Africa' | 'West Africa' | 'Southern Africa' | 'Central Africa' | 'North Africa' | 'Europe' | 'North America' | 'Asia' | 'Latin America' | 'Middle East' | 'Oceania';
  hasDedicatedFrameworkPack: boolean;
  educationAuthority?: string;
  supportedPaymentMethods: string[];
}

export const GLOBAL_COUNTRIES_LIST: GlobalCountryInfo[] = [
  // --- Dedicated Regional Packs ---
  {
    code: 'UG',
    iso3: 'UGA',
    name: 'Uganda',
    officialName: 'Republic of Uganda',
    flagEmoji: '🇺🇬',
    defaultCurrency: 'UGX',
    currencySymbol: 'USh',
    defaultTimezone: 'Africa/Kampala',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Luganda', 'Swahili', 'Runyankole', 'Acholi'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+256',
    frameworkPackCode: 'UG',
    region: 'East Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Ministry of Education and Sports (MoES) / UNEB',
    supportedPaymentMethods: ['MTN Mobile Money', 'Airtel Money', 'Pesapal Gateway', 'Bank Wire / EFT', 'Cash'],
  },
  {
    code: 'KE',
    iso3: 'KEN',
    name: 'Kenya',
    officialName: 'Republic of Kenya',
    flagEmoji: '🇰🇪',
    defaultCurrency: 'KES',
    currencySymbol: 'KSh',
    defaultTimezone: 'Africa/Nairobi',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Kiswahili'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+254',
    frameworkPackCode: 'KE',
    region: 'East Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Ministry of Education (MoE) / KNEC / KICD',
    supportedPaymentMethods: ['M-PESA STK Push', 'M-PESA Paybill / Till', 'Airtel Money Kenya', 'Pesapal Kenya', 'KCB / Equity Bank EFT', 'Cash'],
  },
  {
    code: 'TZ',
    iso3: 'TZA',
    name: 'Tanzania',
    officialName: 'United Republic of Tanzania',
    flagEmoji: '🇹🇿',
    defaultCurrency: 'TZS',
    currencySymbol: 'TSh',
    defaultTimezone: 'Africa/Dar_es_Salaam',
    defaultLanguage: 'Swahili',
    supportedLanguages: ['Swahili', 'English'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+255',
    frameworkPackCode: 'TZ',
    region: 'East Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Ministry of Education, Science and Technology (MoEST) / NECTA',
    supportedPaymentMethods: ['M-Pesa Tanzania', 'Tigo Pesa', 'Airtel Money TZ', 'CRDB / NMB Bank Integration', 'Cash'],
  },
  {
    code: 'RW',
    iso3: 'RWA',
    name: 'Rwanda',
    officialName: 'Republic of Rwanda',
    flagEmoji: '🇷🇼',
    defaultCurrency: 'RWF',
    currencySymbol: 'FRw',
    defaultTimezone: 'Africa/Kigali',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Kinyarwanda', 'French', 'Swahili'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+250',
    frameworkPackCode: 'RW',
    region: 'East Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Ministry of Education (MINEDUC) / NESA / REB',
    supportedPaymentMethods: ['MTN MoMo Rwanda', 'Airtel Money Rwanda', 'BK / I&M Bank Transfer', 'Cash'],
  },
  {
    code: 'GH',
    iso3: 'GHA',
    name: 'Ghana',
    officialName: 'Republic of Ghana',
    flagEmoji: '🇬🇭',
    defaultCurrency: 'GHS',
    currencySymbol: 'GH₵',
    defaultTimezone: 'Africa/Accra',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Twi', 'Ga', 'Ewe', 'Fante'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+233',
    frameworkPackCode: 'GH',
    region: 'West Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Ministry of Education (MoE) / GES / NaCCA / WAEC',
    supportedPaymentMethods: ['MTN MoMo Ghana', 'Telecel Cash', 'Paystack Ghana', 'GCB / Ecobank EFT', 'Cash'],
  },
  {
    code: 'NG',
    iso3: 'NGA',
    name: 'Nigeria',
    officialName: 'Federal Republic of Nigeria',
    flagEmoji: '🇳🇬',
    defaultCurrency: 'NGN',
    currencySymbol: '₦',
    defaultTimezone: 'Africa/Lagos',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Yoruba', 'Hausa', 'Igbo', 'Pidgin'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+234',
    frameworkPackCode: 'NG',
    region: 'West Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Federal Ministry of Education / NERDC / WAEC / NECO',
    supportedPaymentMethods: ['Paystack Direct Debit', 'Flutterwave', 'Monnify', 'Interswitch / Quickteller', 'NIBSS Instant Payment (NIP)', 'Cash'],
  },
  {
    code: 'ZA',
    iso3: 'ZAF',
    name: 'South Africa',
    officialName: 'Republic of South Africa',
    flagEmoji: '🇿🇦',
    defaultCurrency: 'ZAR',
    currencySymbol: 'R',
    defaultTimezone: 'Africa/Johannesburg',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'isiZulu', 'isiXhosa', 'Afrikaans', 'Sepedi', 'Setswana'],
    defaultDateFormat: 'YYYY/MM/DD',
    phonePrefix: '+27',
    frameworkPackCode: 'ZA',
    region: 'Southern Africa',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Department of Basic Education (DBE) / UMALUSI',
    supportedPaymentMethods: ['Ozow Instant EFT', 'PayFast South Africa', 'SnapScan', 'Standard Bank / FNB / Nedbank EFT', 'Cash'],
  },
  {
    code: 'INTL',
    iso3: 'XIN',
    name: 'International (Global Curricula)',
    officialName: 'International School / Cambridge / IB Framework',
    flagEmoji: '🌐',
    defaultCurrency: 'USD',
    currencySymbol: '$',
    defaultTimezone: 'UTC',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'French', 'Spanish', 'German', 'Arabic', 'Mandarin'],
    defaultDateFormat: 'YYYY-MM-DD',
    phonePrefix: '+1',
    frameworkPackCode: 'INTL',
    region: 'Europe',
    hasDedicatedFrameworkPack: true,
    educationAuthority: 'Cambridge International Assessment / International Baccalaureate (IB)',
    supportedPaymentMethods: ['Stripe Global', 'Flywire Tuition', 'PayPal Education', 'International Wire (SWIFT)', 'Credit/Debit Card'],
  },

  // --- Extended African Countries ---
  {
    code: 'SS',
    iso3: 'SSD',
    name: 'South Sudan',
    officialName: 'Republic of South Sudan',
    flagEmoji: '🇸🇸',
    defaultCurrency: 'SSP',
    currencySymbol: 'SSP',
    defaultTimezone: 'Africa/Juba',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Arabic'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+211',
    frameworkPackCode: 'UG', // East African Community curriculum alignment
    region: 'East Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of General Education and Instruction',
    supportedPaymentMethods: ['m-GURUSH', 'Bank Wire', 'Cash'],
  },
  {
    code: 'ET',
    iso3: 'ETH',
    name: 'Ethiopia',
    officialName: 'Federal Democratic Republic of Ethiopia',
    flagEmoji: '🇪🇹',
    defaultCurrency: 'ETB',
    currencySymbol: 'Br',
    defaultTimezone: 'Africa/Addis_Ababa',
    defaultLanguage: 'English',
    supportedLanguages: ['Amharic', 'English', 'Oromo', 'Tigrinya'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+251',
    frameworkPackCode: 'INTL',
    region: 'East Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education (MoE Ethiopia)',
    supportedPaymentMethods: ['Telebirr', 'CBE Birr', 'Bank Wire', 'Cash'],
  },
  {
    code: 'ZM',
    iso3: 'ZMB',
    name: 'Zambia',
    officialName: 'Republic of Zambia',
    flagEmoji: '🇿🇲',
    defaultCurrency: 'ZMW',
    currencySymbol: 'ZK',
    defaultTimezone: 'Africa/Lusaka',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Bemba', 'Nyanja', 'Tonga'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+260',
    frameworkPackCode: 'ZA', // SADC alignment
    region: 'Southern Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of General Education / ECZ',
    supportedPaymentMethods: ['MTN Mobile Money Zambia', 'Airtel Money Zambia', 'Zanaco Bank EFT', 'Cash'],
  },
  {
    code: 'ZW',
    iso3: 'ZWE',
    name: 'Zimbabwe',
    officialName: 'Republic of Zimbabwe',
    flagEmoji: '🇿🇼',
    defaultCurrency: 'USD',
    currencySymbol: '$',
    defaultTimezone: 'Africa/Harare',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Shona', 'Ndebele'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+263',
    frameworkPackCode: 'ZA',
    region: 'Southern Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Primary and Secondary Education / ZIMSEC',
    supportedPaymentMethods: ['EcoCash', 'OneMoney', 'Bank EFT', 'Cash'],
  },
  {
    code: 'BW',
    iso3: 'BWA',
    name: 'Botswana',
    officialName: 'Republic of Botswana',
    flagEmoji: '🇧🇼',
    defaultCurrency: 'BWP',
    currencySymbol: 'P',
    defaultTimezone: 'Africa/Gaborone',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Setswana'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+267',
    frameworkPackCode: 'ZA',
    region: 'Southern Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Basic Education / BEC',
    supportedPaymentMethods: ['Orange Money', 'MyZaka', 'FNB Botswana EFT', 'Cash'],
  },
  {
    code: 'NA',
    iso3: 'NAM',
    name: 'Namibia',
    officialName: 'Republic of Namibia',
    flagEmoji: '🇳🇦',
    defaultCurrency: 'NAD',
    currencySymbol: 'N$',
    defaultTimezone: 'Africa/Windhoek',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Afrikaans', 'Oshiwambo', 'German'],
    defaultDateFormat: 'YYYY/MM/DD',
    phonePrefix: '+264',
    frameworkPackCode: 'ZA',
    region: 'Southern Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education, Arts and Culture',
    supportedPaymentMethods: ['PayToday', 'FNB eWallet', 'Bank EFT', 'Cash'],
  },
  {
    code: 'MW',
    iso3: 'MWI',
    name: 'Malawi',
    officialName: 'Republic of Malawi',
    flagEmoji: '🇲🇼',
    defaultCurrency: 'MWK',
    currencySymbol: 'MK',
    defaultTimezone: 'Africa/Blantyre',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Chichewa'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+265',
    frameworkPackCode: 'UG',
    region: 'East Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education / MANEB',
    supportedPaymentMethods: ['Airtel Money Malawi', 'TNM Mpamba', 'National Bank EFT', 'Cash'],
  },
  {
    code: 'CM',
    iso3: 'CMR',
    name: 'Cameroon',
    officialName: 'Republic of Cameroon',
    flagEmoji: '🇨🇲',
    defaultCurrency: 'XAF',
    currencySymbol: 'FCFA',
    defaultTimezone: 'Africa/Douala',
    defaultLanguage: 'French',
    supportedLanguages: ['French', 'English'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+237',
    frameworkPackCode: 'GH',
    region: 'Central Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Secondary Education (MINESEC)',
    supportedPaymentMethods: ['MTN MoMo Cameroon', 'Orange Money Cameroon', 'Bank EFT', 'Cash'],
  },
  {
    code: 'CI',
    iso3: 'CIV',
    name: 'Ivory Coast (Côte d\'Ivoire)',
    officialName: 'Republic of Côte d\'Ivoire',
    flagEmoji: '🇨🇮',
    defaultCurrency: 'XOF',
    currencySymbol: 'CFA',
    defaultTimezone: 'Africa/Abidjan',
    defaultLanguage: 'French',
    supportedLanguages: ['French'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+225',
    frameworkPackCode: 'GH',
    region: 'West Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministère de l\'Éducation Nationale et de l\'Alphabétisation',
    supportedPaymentMethods: ['Orange Money CI', 'MTN MoMo CI', 'Wave Côte d\'Ivoire', 'Cash'],
  },
  {
    code: 'SN',
    iso3: 'SEN',
    name: 'Senegal',
    officialName: 'Republic of Senegal',
    flagEmoji: '🇸🇳',
    defaultCurrency: 'XOF',
    currencySymbol: 'CFA',
    defaultTimezone: 'Africa/Dakar',
    defaultLanguage: 'French',
    supportedLanguages: ['French', 'Wolof'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+221',
    frameworkPackCode: 'GH',
    region: 'West Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministère de l\'Éducation Nationale',
    supportedPaymentMethods: ['Wave Senegal', 'Orange Money Senegal', 'Free Money', 'Cash'],
  },
  {
    code: 'EG',
    iso3: 'EGY',
    name: 'Egypt',
    officialName: 'Arab Republic of Egypt',
    flagEmoji: '🇪🇬',
    defaultCurrency: 'EGP',
    currencySymbol: 'E£',
    defaultTimezone: 'Africa/Cairo',
    defaultLanguage: 'Arabic',
    supportedLanguages: ['Arabic', 'English', 'French'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+20',
    frameworkPackCode: 'INTL',
    region: 'North Africa',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education and Technical Education (MoETE)',
    supportedPaymentMethods: ['Fawry', 'Vodafone Cash', 'InstaPay Egypt', 'Bank Wire', 'Cash'],
  },

  // --- Americas, Europe, Asia & Middle East (Global Scale) ---
  {
    code: 'GB',
    iso3: 'GBR',
    name: 'United Kingdom',
    officialName: 'United Kingdom of Great Britain and Northern Ireland',
    flagEmoji: '🇬🇧',
    defaultCurrency: 'GBP',
    currencySymbol: '£',
    defaultTimezone: 'Europe/London',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Welsh'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+44',
    frameworkPackCode: 'INTL',
    region: 'Europe',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Department for Education (DfE) / Ofqual',
    supportedPaymentMethods: ['Stripe UK', 'Bacs Direct Debit', 'Faster Payments Bank Transfer', 'Debit/Credit Card'],
  },
  {
    code: 'US',
    iso3: 'USA',
    name: 'United States',
    officialName: 'United States of America',
    flagEmoji: '🇺🇸',
    defaultCurrency: 'USD',
    currencySymbol: '$',
    defaultTimezone: 'America/New_York',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Spanish'],
    defaultDateFormat: 'MM/DD/YYYY',
    phonePrefix: '+1',
    frameworkPackCode: 'INTL',
    region: 'North America',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'US Department of Education / State Boards of Education',
    supportedPaymentMethods: ['Stripe ACH', 'Credit/Debit Cards', 'Apple Pay', 'Google Pay', 'Wire Transfer'],
  },
  {
    code: 'CA',
    iso3: 'CAN',
    name: 'Canada',
    officialName: 'Canada',
    flagEmoji: '🇨🇦',
    defaultCurrency: 'CAD',
    currencySymbol: 'C$',
    defaultTimezone: 'America/Toronto',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'French'],
    defaultDateFormat: 'YYYY-MM-DD',
    phonePrefix: '+1',
    frameworkPackCode: 'INTL',
    region: 'North America',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Provincial Ministries of Education',
    supportedPaymentMethods: ['Interac e-Transfer', 'Stripe Canada', 'EFT Direct Deposit', 'Credit Card'],
  },
  {
    code: 'AE',
    iso3: 'ARE',
    name: 'United Arab Emirates',
    officialName: 'United Arab Emirates',
    flagEmoji: '🇦🇪',
    defaultCurrency: 'AED',
    currencySymbol: 'AED',
    defaultTimezone: 'Asia/Dubai',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Arabic'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+971',
    frameworkPackCode: 'INTL',
    region: 'Middle East',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education (MoE UAE) / KHDA Dubai / ADEK',
    supportedPaymentMethods: ['Stripe UAE', 'PayBy', 'UAE Central Bank Direct Debit', 'Bank Wire'],
  },
  {
    code: 'QA',
    iso3: 'QAT',
    name: 'Qatar',
    officialName: 'State of Qatar',
    flagEmoji: '🇶🇦',
    defaultCurrency: 'QAR',
    currencySymbol: 'QR',
    defaultTimezone: 'Asia/Qatar',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Arabic'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+974',
    frameworkPackCode: 'INTL',
    region: 'Middle East',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education and Higher Education (MOEHE Qatar)',
    supportedPaymentMethods: ['QNB Payment Gateway', 'Stripe', 'Debit/Credit Cards', 'Bank Wire'],
  },
  {
    code: 'IN',
    iso3: 'IND',
    name: 'India',
    officialName: 'Republic of India',
    flagEmoji: '🇮🇳',
    defaultCurrency: 'INR',
    currencySymbol: '₹',
    defaultTimezone: 'Asia/Kolkata',
    defaultLanguage: 'English',
    supportedLanguages: ['English', 'Hindi', 'Tamil', 'Telugu', 'Bengali', 'Marathi'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+91',
    frameworkPackCode: 'INTL',
    region: 'Asia',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Ministry of Education / CBSE / CISCE / State Boards',
    supportedPaymentMethods: ['UPI (Google Pay, PhonePe, Paytm)', 'Razorpay', 'NetBanking', 'Debit/Credit Cards'],
  },
  {
    code: 'AU',
    iso3: 'AUS',
    name: 'Australia',
    officialName: 'Commonwealth of Australia',
    flagEmoji: '🇦🇺',
    defaultCurrency: 'AUD',
    currencySymbol: 'A$',
    defaultTimezone: 'Australia/Sydney',
    defaultLanguage: 'English',
    supportedLanguages: ['English'],
    defaultDateFormat: 'DD/MM/YYYY',
    phonePrefix: '+61',
    frameworkPackCode: 'INTL',
    region: 'Oceania',
    hasDedicatedFrameworkPack: false,
    educationAuthority: 'Australian Curriculum, Assessment and Reporting Authority (ACARA)',
    supportedPaymentMethods: ['Direct Debit (BECS)', 'Stripe Australia', 'BPAY', 'Credit/Debit Card'],
  },
];

export class GlobalCountriesService {
  /**
   * Search and filter countries by name, code, region, currency or phone prefix
   */
  static searchCountries(query: string): GlobalCountryInfo[] {
    if (!query || !query.trim()) {
      return GLOBAL_COUNTRIES_LIST;
    }
    const clean = query.trim().toLowerCase();
    return GLOBAL_COUNTRIES_LIST.filter(
      (c) =>
        c.name.toLowerCase().includes(clean) ||
        c.officialName.toLowerCase().includes(clean) ||
        c.code.toLowerCase().includes(clean) ||
        c.iso3.toLowerCase().includes(clean) ||
        c.defaultCurrency.toLowerCase().includes(clean) ||
        c.region.toLowerCase().includes(clean) ||
        c.phonePrefix.includes(clean)
    );
  }

  /**
   * Get specific country by ISO code or fallback
   */
  static getCountryByCode(code: string): GlobalCountryInfo {
    const found = GLOBAL_COUNTRIES_LIST.find(
      (c) => c.code.toUpperCase() === code.toUpperCase() || c.iso3.toUpperCase() === code.toUpperCase()
    );
    if (found) return found;

    // Fallback: match Uganda if code is empty or not found
    return (
      GLOBAL_COUNTRIES_LIST.find((c) => c.code === 'UG') || GLOBAL_COUNTRIES_LIST[0]
    );
  }

  /**
   * Get all active and supported countries
   */
  static getAllCountries(): GlobalCountryInfo[] {
    return GLOBAL_COUNTRIES_LIST;
  }
}
